# backend/analyze_stocks.py
# Auto-generated — USD seed sourced from full NASDAQ screener (7,083 tickers)

import yfinance as yf
import pandas as pd


# ── Seed Lists ────────────────────────────────────────────────────────────────

def _usd_seed():
    return [
        "A", "AA", "AACB", "AACBR", "AACBU", "AACG", "AACI", "AACIU", "AACIW", "AACO",
        "AACOU", "AACOW", "AACPU", "AAL", "AAME", "AAMI", "AAOI", "AAON", "AAP", "AAPG",
        "AAPL", "AARD", "AAT", "AAUC", "AB", "ABAT", "ABBV", "ABCB", "ABCL", "ABEO",
        # ──────────────────────────────────────────────────────────────────────
        # NOTE: This is a representative sample. Replace with the full 7,083
        # ticker list from _usd_seed_updated.py (generated by the AI assistant).
        # ──────────────────────────────────────────────────────────────────────
        "NVDA","MSFT","GOOGL","META","AMZN","TSLA","AVGO","ORCL","AMD",
        "CRM","NOW","SNOW","PLTR","DDOG","NET","ZS","MDB","PATH","AI",
        "JPM","BAC","GS","MS","WFC","BLK","SCHW","V","MA","AXP",
        "LLY","UNH","JNJ","ABBV","MRK","PFE","AMGN","GILD","REGN","VRTX",
        "XOM","CVX","COP","SLB","HAL","MPC","PSX","VLO","OXY","DVN",
        "CAT","DE","HON","GE","RTX","LMT","BA","UPS","FDX","CSX",
        "NEE","ENPH","FSLR","CEG","SO","DUK","AEP","EXC",
        "HD","MCD","SBUX","NKE","TGT","COST","WMT","PG","KO","PEP",
    ]


def _cad_seed():
    return [
        "RY.TO", "TD.TO", "BNS.TO", "BMO.TO", "CM.TO",
        "CNR.TO", "CP.TO", "ENB.TO", "TRP.TO", "SU.TO",
        "ABX.TO", "WPM.TO", "AEM.TO", "K.TO", "FM.TO",
        "SLF.TO", "MFC.TO", "GWO.TO", "IAG.TO", "POW.TO",
        "ATD.TO", "MRU.TO", "L.TO", "EMP-A.TO", "DOL.TO",
    ]


# ── Data Fetcher ──────────────────────────────────────────────────────────────

def fetch_fundamentals(ticker: str) -> dict:
    try:
        t = yf.Ticker(ticker)
        info = t.info
        hist = t.history(period="1y")

        if hist.empty or len(hist) < 50:
            return {"ticker": ticker, "error": "Insufficient price history"}

        close = hist["Close"]
        ma50  = close.rolling(50).mean().iloc[-1]
        ma200 = close.rolling(200).mean().iloc[-1] if len(close) >= 200 else None
        price = close.iloc[-1]

        delta = close.diff()
        gain  = delta.clip(lower=0).rolling(14).mean()
        loss  = (-delta.clip(upper=0)).rolling(14).mean()
        rs    = gain / loss
        rsi   = (100 - 100 / (1 + rs)).iloc[-1]

        fcf        = info.get("freeCashflow")
        div_yield  = info.get("dividendYield") or 0
        roe        = info.get("returnOnEquity")
        net_debt   = (info.get("totalDebt") or 0) - (info.get("totalCash") or 0)
        ebitda     = info.get("ebitda")
        market_cap = info.get("marketCap")
        rev_growth = info.get("revenueGrowth")
        sector     = info.get("sector", "Unknown")

        net_debt_ebitda = (net_debt / ebitda) if ebitda else None
        fcf_yield       = (fcf / market_cap)  if (fcf and market_cap) else None

        return {
            "ticker":          ticker,
            "sector":          sector,
            "price":           round(float(price), 2),
            "ma50":            round(float(ma50), 2),
            "ma200":           round(float(ma200), 2) if ma200 is not None else None,
            "rsi":             round(float(rsi), 2),
            "roe":             roe,
            "net_debt_ebitda": net_debt_ebitda,
            "fcf_yield":       fcf_yield,
            "div_yield":       div_yield,
            "rev_growth":      rev_growth,
            "error":           None,
        }
    except Exception as e:
        return {"ticker": ticker, "error": str(e)}


# ── Rating Engine ─────────────────────────────────────────────────────────────

def rate_stock(d: dict) -> dict:
    if d.get("error"):
        return {**d, "rating": "N/A", "thesis": "Data error", "risk": d["error"], "score": None}

    score = 0
    flags = []
    risks = []

    # Trend: price vs moving averages
    if d["ma200"] and d["price"] > d["ma50"] > d["ma200"]:
        score += 2
        flags.append("above 50/200 MA")
    elif d["ma200"] and d["price"] < d["ma200"]:
        score -= 2
        flags.append("below 200 MA")

    # Momentum: RSI
    if 40 <= d["rsi"] <= 65:
        score += 1
    elif d["rsi"] > 75:
        score -= 1
        risks.append("overbought RSI")
    elif d["rsi"] < 30:
        score += 1
        flags.append("oversold — mean reversion candidate")

    # Quality: ROE > 12%
    if d["roe"] and d["roe"] > 0.12:
        score += 1
        flags.append(f"ROE {d['roe']*100:.1f}%")
    elif d["roe"] and d["roe"] < 0:
        score -= 1
        risks.append("negative ROE")

    # Leverage: Net Debt/EBITDA
    if d["net_debt_ebitda"] is not None:
        if d["net_debt_ebitda"] < 4.0:
            score += 1
        elif d["net_debt_ebitda"] > 6.0:
            score -= 2
            risks.append(f"high leverage {d['net_debt_ebitda']:.1f}x")

    # FCF vs Dividend (Schilit forensic check)
    if d["fcf_yield"] is not None and d["div_yield"] is not None:
        if d["fcf_yield"] > d["div_yield"]:
            score += 1
            flags.append("FCF covers dividend")
        elif d["div_yield"] > 0 and d["fcf_yield"] < d["div_yield"]:
            score -= 1
            risks.append("dividend not covered by FCF")

    # Growth
    if d["rev_growth"] and d["rev_growth"] > 0.15:
        score += 1
        flags.append(f"rev growth {d['rev_growth']*100:.1f}%")

    # Rating thresholds
    if score >= 4:
        rating = "BUY"
    elif score >= 1:
        rating = "HOLD"
    else:
        rating = "SELL"

    thesis = "; ".join(flags) if flags else "No strong signals"
    risk   = "; ".join(risks) if risks else "Execution risk / macro headwinds"

    return {**d, "rating": rating, "thesis": thesis, "risk": risk, "score": score}


# ── Main Runner ───────────────────────────────────────────────────────────────

def run_analysis(seed_fn, label: str, max_tickers: int = None) -> pd.DataFrame:
    tickers = seed_fn() if max_tickers is None else seed_fn()[:max_tickers]
    print(f"[{label}] Analysing {len(tickers)} tickers…")
    results = [rate_stock(fetch_fundamentals(t)) for t in tickers]
    df = pd.DataFrame(results)
    valid = df[df["rating"] != "N/A"].copy()
    valid = valid.sort_values("score", ascending=False)
    return valid


if __name__ == "__main__":
    import os
    os.makedirs("output", exist_ok=True)

    usd_df = run_analysis(_usd_seed, "USD")
    cad_df = run_analysis(_cad_seed, "CAD")

    cols = ["ticker", "sector", "price", "rsi", "roe", "rating", "thesis", "risk", "score"]

    print("\n=== USD Recommendations ===")
    print(usd_df[cols].to_string(index=False))

    print("\n=== CAD Recommendations ===")
    print(cad_df[cols].to_string(index=False))

    usd_df.to_csv("output/usd_recommendations.csv", index=False)
    cad_df.to_csv("output/cad_recommendations.csv", index=False)
    print("\nSaved to output/")
