# backend/analyze_stocks.py
# Writes public/recommendations.json consumed by the React dashboard

import os
import json
import yfinance as yf
import pandas as pd


# ── Seed Lists ────────────────────────────────────────────────────────────────

def _usd_seed():
    return [
        "A", "AA", "AACB", "AACBR", "AACBU", "AACG", "AACI", "AACIU", "AACIW", "AACO",
        "AACOU", "AACOW", "AACPU", "AAL", "AAME", "AAMI", "AAOI", "AAON", "AAP", "AAPG",
        "AAPL", "AARD", "AAT", "AAUC", "AB", "ABAT", "ABBV", "ABCB", "ABCL", "ABEO",
        "ABEV", "ABG", "ABLV", "ABLVW", "ABM", "ABNB", "ABOS", "ABR", "ABR^D", "ABR^E",
        "ABR^F", "ABSI", "ABT", "ABTC", "ABTS", "ABUS", "ABVC", "ABVE", "ABVEW", "ABVX",
        "ABX", "ABXL", "ACA", "ACAA", "ACAAU", "ACAAW", "ACAD", "ACB", "ACCL", "ACCO",
        "ACCS", "ACDC", "ACEL", "ACET", "ACFN", "ACGCU", "ACGL", "ACGLN", "ACGLO", "ACH",
        "ACHC", "ACHR", "ACHV", "ACI", "ACIC", "ACIU", "ACIW", "ACLS", "ACLX", "ACM",
        "ACMR", "ACN", "ACNB", "ACNT", "ACOG", "ACON", "ACONW", "ACP", "ACP^A", "ACR",
        "ACR^C", "ACR^D", "ACRE", "ACRS", "ACRV", "ACT", "ACTG", "ACTU", "ACU", "ACV",
        "ACVA", "ACXP", "AD", "ADAC", "ADACW", "ADAG", "ADAM", "ADAMG", "ADAMH", "ADAMI",
        "ADAML", "ADAMM", "ADAMN", "ADAMO", "ADAMZ", "ADBE", "ADC", "ADC^A", "ADCT", "ADEA",
        "ADGM", "ADI", "ADIL", "ADM", "ADMA", "ADNT", "ADP", "ADPT", "ADSE", "ADSEW",
        "ADSK", "ADT", "ADTN", "ADTX", "ADUR", "ADUS", "ADV", "ADVB", "ADX", "ADXN",
        "AEAQW", "AEBI", "AEC", "AEE", "AEF", "AEFC", "AEG", "AEHL", "AEHR", "AEI",
        "AEIS", "AEM", "AEMD", "AENT", "AENTW", "AEO", "AEON", "AEP", "AER", "AERO",
        "AERT", "AERTW", "AES", "AESI", "AEVA", "AEXA", "AEYE", "AFB", "AFBI", "AFCG",
        "AFG", "AFGB", "AFGC", "AFGD", "AFGE", "AFJK", "AFJKR", "AFJKU", "AFL", "AFRI",
        "AFRIW", "AFRM", "AFYA", "AG", "AGAE", "AGBK", "AGCC", "AGCO", "AGD", "AGEN",
        "AGH", "AGI", "AGIG", "AGIO", "AGL", "AGM", "AGM^D", "AGM^E", "AGM^F", "AGM^G",
        "AGM^H", "AGMB", "AGMH", "AGNC", "AGNCL", "AGNCM", "AGNCN", "AGNCO", "AGNCP", "AGNCZ",
        "AGO", "AGPU", "AGRO", "AGRZ", "AGX", "AGYS", "AHCO", "AHG", "AHL^D", "AHL^E",
        "AHL^F", "AHMA", "AHR", "AHRT", "AHRT^A", "AHT", "AHT^D", "AHT^F", "AHT^G", "AHT^H",
        "AHT^I", "AI", "AIB", "AIDX", "AIFF", "AIFU", "AIG", "AIHS", "AII", "AIIA",
        "AIIO", "AIIOW", "AIM", "AIMD", "AIMDW", "AIN", "AIO", "AIOS", "AIOT", "AIP",
        "AIR", "AIRE", "AIRG", "AIRI", "AIRJ", "AIRJW", "AIRO", "AIRS", "AIRT", "AIRTP",
        "AISP", "AISPW", "AIT", "AIV", "AIXC", "AIXI", "AIZ", "AIZN", "AJG", "AKA",
        "AKAM", "AKAN", "AKBA", "AKO/A", "AKO/B", "AKR", "AKTS", "AKTX", "ALAB", "ALAR",
        "ALB", "ALB^A", "ALBT", "ALC", "ALCO", "ALCY", "ALCYU", "ALCYW", "ALDF", "ALDFU",
        "ALDFW", "ALDX", "ALEC", "ALF", "ALFUU", "ALG", "ALGM", "ALGN", "ALGS", "ALGT",
        "ALH", "ALHC", "ALIS", "ALISR", "ALISU", "ALIT", "ALK", "ALKS", "ALKT", "ALL",
        "ALL^B", "ALL^H", "ALL^I", "ALL^J", "ALLE", "ALLO", "ALLR", "ALLT", "ALLY", "ALM",
        "ALMR", "ALMS", "ALMU", "ALNT", "ALNY", "ALOT", "ALOV", "ALOVU", "ALOVW", "ALOY",
        "ALP", "ALPS", "ALRM", "ALRS", "ALSN", "ALT", "ALTG", "ALTG^A", "ALTI", "ALTO",
        "ALTS", "ALV", "ALVO", "ALVOW", "ALX", "ALXO", "ALZN", "AM", "AMAL", "AMAT",
        "AMBA", "AMBO", "AMBP", "AMBQ", "AMBR", "AMC", "AMCI", "AMCR", "AMCX", "AMD",
        "AME", "AMG", "AMGN", "AMH", "AMH^G", "AMH^H", "AMIX", "AMKR", "AMLX", "AMN",
        "AMOD", "AMODW", "AMP", "AMPG", "AMPGR", "AMPGZ", "AMPH", "AMPL", "AMPX", "AMPY",
        "AMR", "AMRC", "AMRN", "AMRX", "AMRZ", "AMS", "AMSC", "AMSF", "AMST", "AMT",
        "AMTB", "AMTD", "AMTM", "AMTX", "AMWD", "AMWL", "AMX", "AMZE", "AMZN", "AN",
        "ANAB", "ANDE", "ANDG", "ANET", "ANF", "ANG^D", "ANGH", "ANGHW", "ANGI", "ANGO",
        "ANGX", "ANIK", "ANIP", "ANIX", "ANL", "ANNA", "ANNAW", "ANNX", "ANPA", "ANRO",
        "ANSC", "ANSCW", "ANTA", "ANTX", "ANVS", "ANY", "AOD", "AOMD", "AOMN", "AOMR",
        "AON", "AORT", "AOS", "AOSL", "AOUT", "AP", "APA", "APAC", "APACR", "APACU",
        "APAD", "APADR", "APADU", "APAM", "APC", "APD", "APEI", "APG", "APGE", "APH",
        "API", "APLD", "APLE", "APLM", "APLMW", "APLS", "APM", "APO", "APO^A", "APOG",
        "APOS", "APP", "APPF", "APPN", "APPS", "APRE", "APT", "APTV", "APVO", "APWC",
        "APXT", "APXTU", "APXTW", "APYX", "AQB", "AQMS", "AQN", "AQNB", "AQST", "AR",
        "ARAI", "ARAY", "ARBB", "ARBE", "ARBEW", "ARBK", "ARCB", "ARCC", "ARCI", "ARCIU",
        "ARCIW", "ARCO", "ARCT", "ARDC", "ARDT", "ARDX", "ARE", "AREC", "AREN", "ARES",
        "ARES^B", "ARGX", "ARHS", "ARI", "ARIS", "ARKO", "ARKR", "ARL", "ARLO", "ARLP",
        "ARM", "ARMK", "ARMP", "AROC", "AROW", "ARQ", "ARQQ", "ARQQW", "ARQT", "ARR",
        "ARR^C", "ARRY", "ARTC", "ARTCU", "ARTCW", "ARTL", "ARTNA", "ARTV", "ARTW", "ARVN",
        "ARW", "ARWR", "ARX", "ARXS", "AS", "ASA", "ASAN", "ASB", "ASB^E", "ASB^F",
        "ASBA", "ASBP", "ASBPW", "ASC", "ASG", "ASGI", "ASH", "ASIC", "ASIX", "ASLE",
        "ASM", "ASMB", "ASML", "ASND", "ASO", "ASPC", "ASPCU", "ASPI", "ASPN", "ASPS",
        "ASPSW", "ASPSZ", "ASR", "ASRT", "ASRV", "ASST", "ASTC", "ASTE", "ASTH", "ASTI",
        "ASTL", "ASTLW", "ASTS", "ASUR", "ASX", "ASYS", "ATAI", "ATAT", "ATCH", "ATCX",
        "ATEC", "ATEN", "ATER", "ATEX", "ATGL", "ATH^A", "ATH^B", "ATH^D", "ATH^E", "ATHE",
        "ATHM", "ATHR", "ATHS", "ATI", "ATII", "ATIIU", "ATIIW", "ATKR", "ATLC", "ATLCL",
        "ATLCP", "ATLCZ", "ATLN", "ATLO", "ATLX", "ATMU", "ATNI", "ATNM", "ATO", "ATOM",
        "ATOS", "ATPC", "ATR", "ATRA", "ATRC", "ATRO", "ATS", "ATXG", "ATYR", "AU",
        "AUB", "AUB^A", "AUBN", "AUDC", "AUGO", "AUID", "AUNA", "AUPH", "AUR", "AURA",
        "AURE", "AUROW", "AUST", "AUTL", "AUUD", "AVA", "AVAH", "AVAL", "AVAV", "AVB",
        "AVBC", "AVBH", "AVBP", "AVD", "AVEX", "AVGO", "AVIR", "AVK", "AVNS", "AVNT",
        "AVNW", "AVO", "AVPT", "AVR", "AVT", "AVTR", "AVTX", "AVX", "AVXL", "AVY",
        "AWF", "AWI", "AWK", "AWP", "AWR", "AWRE", "AWX", "AX", "AXG", "AXGN",
        "AXIA", "AXIA^", "AXIA^C", "AXIL", "AXIN", "AXINR", "AXINU", "AXON", "AXP", "AXR",
        "AXS", "AXS^E", "AXSM", "AXTA", "AXTI", "AYI", "AYTU", "AZ", "AZI", "AZN",
        "AZO", "AZTA", "AZTR", "AZZ", "B", "BA", "BA^A", "BABA", "BAC", "BAC^B",
        "BAC^E", "BAC^K", "BAC^L", "BAC^M", "BAC^N", "BAC^O", "BAC^P", "BAC^Q", "BAC^S", "BACC",
        "BACCR", "BAER", "BAERW", "BAFN", "BAH", "BAK", "BALL", "BALY", "BAM", "BANC",
        "BANC^F", "BAND", "BANF", "BANFP", "BANL", "BANR", "BANX", "BAOS", "BAP", "BARK",
        "BATL", "BATRA", "BATRK", "BAX", "BAYA", "BAYAR", "BB", "BBAI", "BBAR", "BBBY",
        "BBCP", "BBCQ", "BBCQU", "BBCQW", "BBD", "BBDC", "BBDO", "BBGI", "BBIO", "BBLG",
        "BBLGW", "BBN", "BBNX", "BBOT", "BBSI", "BBT", "BBUC", "BBVA", "BBW", "BBWI",
        "BBY", "BC", "BC^C", "BCAB", "BCAL", "BCAR", "BCARW", "BCAT", "BCAX", "BCBP",
        "BCC", "BCDA", "BCE", "BCG", "BCGWW", "BCH", "BCHT", "BCIC", "BCML", "BCO",
        "BCPC", "BCRX", "BCS", "BCSF", "BCSS", "BCTX", "BCTXL", "BCTXZ", "BCV", "BCV^A",
        "BCX", "BCYC", "BDC", "BDCI", "BDCIU", "BDCIW", "BDJ", "BDL", "BDMD", "BDMDW",
        "BDN", "BDRX", "BDSX", "BDTX", "BDX", "BE", "BEAG", "BEAGR", "BEAGU", "BEAM",
        "BEAT", "BEATW", "BEBE", "BEEM", "BEEP", "BEKE", "BELFA", "BELFB", "BEN", "BENF",
        "BENFW", "BEP", "BEP^A", "BEPC", "BEPH", "BEPI", "BEPJ", "BESS", "BETA", "BETR",
        "BETRW", "BF/A", "BF/B", "BFAM", "BFC", "BFH", "BFH^A", "BFLY", "BFRG", "BFRGW",
        "BFRI", "BFRIW", "BFS", "BFS^D", "BFS^E", "BFST", "BG", "BGB", "BGC", "BGH",
        "BGI", "BGIN", "BGL", "BGLC", "BGLWW", "BGM", "BGMS", "BGR", "BGS", "BGSF",
        "BGSI", "BGT", "BGX", "BGY", "BH", "BHAV", "BHAVR", "BHAVU", "BHB", "BHC",
        "BHE", "BHF", "BHFAL", "BHFAM", "BHFAN", "BHFAO", "BHFAP", "BHK", "BHM", "BHP",
        "BHR", "BHR^B", "BHR^D", "BHRB", "BHST", "BHV", "BHVN", "BIAF", "BIAFW", "BIDU",
        "BIIB", "BIII", "BILI", "BILL", "BIO", "BIO/B", "BIOA", "BIOX", "BIP", "BIP^A",
        "BIP^B", "BIPC", "BIPH", "BIPI", "BIPJ", "BIRD", "BIRK", "BIT", "BIVI", "BIVIW",
        "BIXI", "BIXIU", "BIXIW", "BIYA", "BJ", "BJDX", "BJRI", "BK", "BK^K", "BKD",
        "BKE", "BKH", "BKKT", "BKNG", "BKR", "BKSY", "BKT", "BKTI", "BKU", "BKV",
        "BKYI", "BL", "BLBD", "BLCO", "BLD", "BLDP", "BLDR", "BLFS", "BLIN", "BLIV",
        "BLK", "BLKB", "BLLN", "BLMN", "BLND", "BLNE", "BLNK", "BLRK", "BLRKU", "BLRKW",
        "BLRX", "BLSH", "BLTE", "BLUW", "BLUWW", "BLW", "BLX", "BLZE", "BLZR", "BLZRU",
        "BLZRW", "BMA", "BMBL", "BME", "BMEA", "BMEZ", "BMGL", "BMHL", "BMI", "BML^G",
        "BML^H", "BML^J", "BML^L", "BMM", "BMN", "BMNR", "BMO", "BMR", "BMRA", "BMRC",
        "BMRN", "BMY", "BN", "BNAI", "BNAIW", "BNBX", "BNC", "BNCWW", "BNCWZ", "BNED",
        "BNGO", "BNH", "BNJ", "BNKK", "BNL", "BNR", "BNRG", "BNS", "BNT", "BNTC",
        "BNTX", "BNZI", "BNZIW", "BOBS", "BOC", "BODI", "BOE", "BOF", "BOH", "BOH^A",
        "BOH^B", "BOKF", "BOLD", "BOLT", "BON", "BOOM", "BOOT", "BORR", "BOSC", "BOTJ",
        "BOW", "BOX", "BOXL", "BP", "BPAC", "BPACR", "BPOP", "BPOPM", "BPRE", "BPRN",
        "BPYPM", "BPYPN", "BPYPO", "BPYPP", "BQ", "BR", "BRAG", "BRAI", "BRBI", "BRBR",
        "BRBS", "BRC", "BRCB", "BRCC", "BRFH", "BRIA", "BRID", "BRK/A", "BRK/B", "BRKR",
        "BRKRP", "BRLS", "BRLSW", "BRLT", "BRN", "BRNS", "BRO", "BROS", "BRR", "BRRWW",
        "BRSL", "BRSP", "BRT", "BRTX", "BRW", "BRX", "BRZE", "BSAA", "BSAAR", "BSAAU",
        "BSAC", "BSBK", "BSBR", "BSET", "BSL", "BSM", "BSRR", "BST", "BSTZ", "BSVN",
        "BSX", "BSY", "BTAI", "BTBD", "BTBDW", "BTBT", "BTCS", "BTCT", "BTDR", "BTE",
        "BTG", "BTGO", "BTI", "BTM", "BTMD", "BTMWW", "BTO", "BTOC", "BTOG", "BTQ",
        "BTSG", "BTSGU", "BTT", "BTTC", "BTU", "BTX", "BTZ", "BUD", "BUDA", "BUI",
        "BULL", "BULLW", "BUR", "BURL", "BURU", "BUSE", "BUSEP", "BUUU", "BV", "BVC",
        "BVFL", "BVN", "BVS", "BW", "BW^A", "BWA", "BWAY", "BWB", "BWBBP", "BWEN",
        "BWFG", "BWG", "BWIN", "BWLP", "BWMN", "BWMX", "BWNB", "BWXT", "BX", "BXC",
        "BXMT", "BXP", "BXSL", "BY", "BYAH", "BYD", "BYFC", "BYND", "BYRN", "BYSI",
        "BZ", "BZAI", "BZAIW", "BZFD", "BZFDW", "BZH", "BZUN", "C", "C^N", "C^R",
        "CAAP", "CAAS", "CABA", "CABO", "CABR", "CAC", "CACC", "CACI", "CADL", "CAE",
        "CAEP", "CAF", "CAG", "CAH", "CAI", "CAKE", "CAL", "CALC", "CALM", "CALX",
        "CALY", "CAMP", "CAMT", "CAN", "CANF", "CANG", "CAPL", "CAPN", "CAPR", "CAPS",
        "CAQ", "CAQUU", "CAR", "CARE", "CARG", "CARL", "CARR", "CARS", "CART", "CASH",
        "CASS", "CAST", "CASY", "CAT", "CATO", "CATX", "CATY", "CAVA", "CB", "CBAN",
        "CBAT", "CBC", "CBFV", "CBIO", "CBK", "CBL", "CBLL", "CBNA", "CBNK", "CBOE",
        "CBRE", "CBRL", "CBSH", "CBT", "CBU", "CBUS", "CBZ", "CC", "CCAP", "CCB",
        "CCBG", "CCC", "CCCC", "CCD", "CCEC", "CCEL", "CCEP", "CCG", "CCGWW", "CCHH",
        "CCI", "CCID", "CCIF", "CCII", "CCIIU", "CCIIW", "CCIX", "CCIXW", "CCJ", "CCK",
        "CCL", "CCLD", "CCLDO", "CCM", "CCNE", "CCNEP", "CCO", "CCOI", "CCRN", "CCS",
        "CCSI", "CCTG", "CCU", "CCXI", "CCXIU", "CCXIW", "CCZ", "CD", "CDE", "CDIO",
        "CDIOW", "CDLR", "CDLX", "CDNA", "CDNL", "CDNS", "CDP", "CDR^B", "CDR^C", "CDRE",
        "CDRO", "CDROW", "CDT", "CDTG", "CDTTW", "CDW", "CDXS", "CDZI", "CDZIP", "CE",
        "CECO", "CEE", "CEG", "CELC", "CELH", "CELU", "CELZ", "CENN", "CENT", "CENTA",
        "CENX", "CEPF", "CEPO", "CEPS", "CEPT", "CEPU", "CEPV", "CERS", "CERT", "CET",
        "CETX", "CETY", "CEV", "CEVA", "CF", "CFBK", "CFFI", "CFFN", "CFG", "CFG^E",
        "CFG^H", "CFG^I", "CFND", "CFR", "CFR^B", "CFTR^A", "CG", "CGABL", "CGAU", "CGBD",
        "CGC", "CGCT", "CGCTU", "CGCTW", "CGEM", "CGEN", "CGNT", "CGNX", "CGO", "CGON",
        "CGTL", "CGTX", "CHA", "CHAI", "CHAR", "CHARR", "CHCI", "CHCO", "CHCT", "CHD",
        "CHDN", "CHE", "CHEC", "CHECU", "CHECW", "CHEF", "CHGG", "CHH", "CHI", "CHKP",
        "CHMG", "CHMI", "CHMI^A", "CHMI^B", "CHNR", "CHOW", "CHPG", "CHPGR", "CHPT", "CHR",
        "CHRD", "CHRS", "CHRW", "CHSCL", "CHSCM", "CHSCN", "CHSCO", "CHSCP", "CHSN", "CHT",
        "CHTR", "CHW", "CHWY", "CHY", "CHYM", "CI", "CIA", "CIB", "CICB", "CICC",
        "CIEN", "CIF", "CIFR", "CIG", "CIGI", "CII", "CIIT", "CIK", "CIM", "CIM^A",
        "CIM^B", "CIM^C", "CIM^D", "CIMN", "CIMO", "CIMP", "CINF", "CING", "CINGW", "CINT",
        "CION", "CISO", "CISS", "CITR", "CIVB", "CIX", "CJMB", "CKX", "CL", "CLAR",
        "CLB", "CLBK", "CLBR", "CLBT", "CLDI", "CLDT", "CLDT^A", "CLDX", "CLF", "CLFD",
        "CLGN", "CLH", "CLIK", "CLIR", "CLLS", "CLM", "CLMB", "CLMT", "CLNE", "CLNN",
        "CLOV", "CLPR", "CLPS", "CLPT", "CLRB", "CLRO", "CLS", "CLSK", "CLSKW", "CLST",
        "CLVT", "CLW", "CLWT", "CLX", "CLYM", "CM", "CMBT", "CMC", "CMCL", "CMCM",
        "CMCO", "CMCSA", "CMCT", "CMDB", "CME", "CMG", "CMI", "CMII", "CMMB", "CMND",
        "CMP", "CMPR", "CMPS", "CMPX", "CMRC", "CMRE", "CMRE^B", "CMRE^C", "CMRE^D", "CMS",
        "CMS^B", "CMS^C", "CMSA", "CMSC", "CMSD", "CMT", "CMTG", "CMTL", "CMTV", "CMU",
        "CNA", "CNC", "CNCK", "CNCKW", "CNDT", "CNET", "CNEY", "CNF", "CNH", "CNI",
        "CNK", "CNL", "CNM", "CNMD", "CNNE", "CNO", "CNO^A", "CNOB", "CNOBP", "CNP",
        "CNQ", "CNR", "CNS", "CNSP", "CNTA", "CNTB", "CNTN", "CNTX", "CNTY", "CNVS",
        "CNX", "CNXC", "CNXN", "COCH", "COCHW", "COCO", "COCP", "CODA", "CODI", "CODI^A",
        "CODI^B", "CODI^C", "CODX", "COE", "COEP", "COEPW", "COF", "COF^I", "COF^J", "COF^K",
        "COF^L", "COF^N", "COFS", "COGT", "COHN", "COHR", "COHU", "COIN", "COKE", "COLA",
        "COLAU", "COLB", "COLD", "COLL", "COLM", "COMP", "CON", "COO", "COOK", "COOT",
        "COOTW", "COP", "COPL", "COR", "CORT", "CORZ", "CORZW", "CORZZ", "COSM", "COSO",
        "COST", "COTY", "COUR", "COYA", "CP", "CPA", "CPAC", "CPAY", "CPB", "CPBI",
        "CPF", "CPHC", "CPHI", "CPIX", "CPK", "CPNG", "CPOP", "CPRI", "CPRT", "CPRX",
        "CPS", "CPSH", "CPSS", "CPT", "CPZ", "CQP", "CR", "CRAC", "CRACR", "CRACU",
        "CRACW", "CRAI", "CRAN", "CRANR", "CRANU", "CRAQ", "CRAQR", "CRAQU", "CRBD", "CRBG",
        "CRBP", "CRBU", "CRC", "CRCL", "CRCT", "CRD/A", "CRD/B", "CRDF", "CRDL", "CRDO",
        "CRE", "CREG", "CRESY", "CREX", "CRF", "CRGO", "CRGOW", "CRGY", "CRH", "CRI",
        "CRIS", "CRK", "CRL", "CRM", "CRMD", "CRML", "CRMLW", "CRMT", "CRNC", "CRNT",
        "CRNX", "CRON", "CROX", "CRS", "CRSP", "CRSR", "CRT", "CRTO", "CRUS", "CRVL",
        "CRVO", "CRVS", "CRWD", "CRWS", "CRWV", "CSAI", "CSAN", "CSBR", "CSCO", "CSGP",
        "CSGS", "CSHR", "CSHRW", "CSIQ", "CSL", "CSPI", "CSQ", "CSR", "CSTE", "CSTL",
        "CSTM", "CSV", "CSW", "CSWC", "CSX", "CTA^A", "CTA^B", "CTAA", "CTAAR", "CTAAU",
        "CTAS", "CTBB", "CTBI", "CTDD", "CTEV", "CTGO", "CTKB", "CTLP", "CTM", "CTMX",
        "CTNM", "CTNT", "CTO", "CTO^A", "CTOR", "CTOS", "CTRA", "CTRE", "CTRI", "CTRM",
        "CTRN", "CTS", "CTSH", "CTSO", "CTVA", "CTW", "CTXR", "CUB", "CUBB", "CUBE",
        "CUBI", "CUBWU", "CUBWW", "CUE", "CUK", "CULP", "CUPR", "CURB", "CURI", "CURR",
        "CURV", "CURX", "CUZ", "CV", "CVBF", "CVCO", "CVE", "CVEO", "CVGI", "CVGW",
        "CVI", "CVKD", "CVLG", "CVLT", "CVM", "CVNA", "CVR", "CVRX", "CVS", "CVSA",
        "CVU", "CVV", "CVX", "CW", "CWAN", "CWBC", "CWCO", "CWD", "CWEN", "CWH",
        "CWK", "CWST", "CWT", "CX", "CXAI", "CXAIW", "CXDO", "CXE", "CXH", "CXM",
        "CXT", "CXW", "CYAB", "CYCN", "CYCU", "CYCUW", "CYD", "CYH", "CYN", "CYPH",
        "CYRX", "CYTK", "CZFS", "CZNC", "CZR", "CZWI", "D", "DAAQ", "DAAQU", "DAAQW",
        "DAC", "DAIC", "DAICW", "DAIO", "DAKT", "DAL", "DAN", "DAO", "DAR", "DARE",
        "DASH", "DAVA", "DAVE", "DAVEW", "DB", "DBCA", "DBCAW", "DBD", "DBGI", "DBI",
        "DBL", "DBRG", "DBRG^H", "DBRG^I", "DBRG^J", "DBVT", "DBX", "DC", "DCBG", "DCBO",
        "DCGO", "DCH", "DCI", "DCO", "DCOM", "DCOM^", "DCOY", "DCTH", "DCX", "DD",
        "DDC", "DDD", "DDI", "DDL", "DDOG", "DDS", "DDT", "DE", "DEA", "DEC",
        "DECK", "DEFT", "DEI", "DELL", "DEO", "DERM", "DETX", "DEVS", "DFDV", "DFDVW",
        "DFH", "DFIN", "DFLI", "DFLIW", "DFNS", "DFNSW", "DFP", "DFSC", "DFSCW", "DFTX",
        "DG", "DGICA", "DGICB", "DGII", "DGNX", "DGX", "DGXX", "DH", "DHC", "DHCNI",
        "DHCNL", "DHF", "DHI", "DHR", "DHT", "DHX", "DHY", "DIBS", "DIN", "DINO",
        "DIOD", "DIS", "DIT", "DJCO", "DJT", "DJTWW", "DK", "DKI", "DKL", "DKNG",
        "DKS", "DLB", "DLHC", "DLNG", "DLNG^A", "DLO", "DLPN", "DLR", "DLR^J", "DLR^K",
        "DLR^L", "DLTH", "DLTR", "DLX", "DLXY", "DLY", "DMA", "DMAA", "DMAAR", "DMAC",
        "DMB", "DMII", "DMIIR", "DMIIU", "DMLP", "DMO", "DMRA", "DMRC", "DNA", "DNLI",
        "DNMX", "DNMXU", "DNMXW", "DNN", "DNOW", "DNP", "DNTH", "DNUT", "DOC", "DOCN",
        "DOCS", "DOCU", "DOGZ", "DOLE", "DOMH", "DOMO", "DOO", "DORM", "DOUG", "DOV",
        "DOW", "DOX", "DOYU", "DPG", "DPRO", "DPZ", "DQ", "DRCT", "DRD", "DRDB",
        "DRDBW", "DRH", "DRI", "DRIO", "DRMA", "DRMAW", "DRS", "DRTS", "DRTSW", "DRUG",
        "DRVN", "DSACU", "DSGN", "DSGR", "DSGX", "DSL", "DSM", "DSP", "DSS", "DSU",
        "DSWL", "DSX", "DSX^B", "DSY", "DSYWW", "DT", "DTB", "DTCX", "DTE", "DTF",
        "DTG", "DTI", "DTIL", "DTK", "DTM", "DTSQ", "DTSQR", "DTSQU", "DTSS", "DTST",
        "DTSTW", "DTW", "DUK", "DUK^A", "DUKB", "DUO", "DUOL", "DUOT", "DV", "DVA",
        "DVLT", "DVN", "DWSN", "DWTX", "DX", "DX^C", "DXC", "DXCM", "DXF", "DXLG",
        "DXPE", "DXR", "DXST", "DXYZ", "DY", "DYAI", "DYN", "DYOR", "DYORU", "E",
        "EA", "EAD", "EAF", "EAI", "EARN", "EAT", "EBAY", "EBC", "EBF", "EBMT",
        "EBON", "EBS", "EC", "ECAT", "ECBK", "ECC", "ECC^D", "ECCC", "ECCU", "ECCV",
        "ECCW", "ECCX", "ECF", "ECF^A", "ECG", "ECL", "ECO", "ECOR", "ECPG", "ECVT",
        "ECX", "ECXWW", "ED", "EDAP", "EDBL", "EDBLW", "EDD", "EDF", "EDHL", "EDIT",
        "EDN", "EDRY", "EDSA", "EDTK", "EDU", "EDUC", "EE", "EEA", "EEFT", "EEIQ",
        "EEX", "EFC", "EFC^B", "EFC^C", "EFC^D", "EFOI", "EFOR", "EFR", "EFSC", "EFSCP",
        "EFSI", "EFT", "EFX", "EFXT", "EG", "EGAN", "EGBN", "EGP", "EGY", "EH",
        "EHAB", "EHC", "EHGO", "EHI", "EHLD", "EHTH", "EIC", "EICA", "EIG", "EIIA",
        "EIKN", "EIM", "EIX", "EJH", "EKSO", "EL", "ELA", "ELAB", "ELAN", "ELBM",
        "ELC", "ELDN", "ELE", "ELF", "ELLA", "ELLO", "ELMD", "ELME", "ELMT", "ELOG",
        "ELPC", "ELPW", "ELS", "ELSE", "ELTK", "ELTX", "ELUT", "ELV", "ELVA", "ELVN",
        "ELVR", "ELWT", "EM", "EMA", "EMAT", "EMBC", "EMBJ", "EMD", "EME", "EMF",
        "EMIS", "EML", "EMN", "EMO", "EMP", "EMPD", "EMR", "ENB", "ENGN", "ENGNW",
        "ENGS", "ENIC", "ENJ", "ENLT", "ENLV", "ENO", "ENOV", "ENPH", "ENR", "ENS",
        "ENSC", "ENSG", "ENTA", "ENTG", "ENTX", "ENVA", "ENVB", "ENVX", "EOD", "EOG",
        "EOI", "EOLS", "EONR", "EOS", "EOSE", "EOT", "EP", "EP^C", "EPAC", "EPAM",
        "EPC", "EPD", "EPM", "EPOW", "EPR", "EPR^C", "EPR^E", "EPR^G", "EPRT", "EPRX",
        "EPSM", "EPSN", "EQ", "EQBK", "EQH", "EQH^A", "EQH^C", "EQIX", "EQNR", "EQPT",
        "EQR", "EQS", "EQT", "EQX", "ERAS", "ERC", "ERH", "ERIC", "ERIE", "ERII",
        "ERNA", "ERNAW", "ERO", "ES", "ESAB", "ESCA", "ESE", "ESEA", "ESHA", "ESHAR",
        "ESI", "ESLA", "ESLAW", "ESLT", "ESNT", "ESOA", "ESP", "ESPR", "ESQ", "ESRT",
        "ESS", "ESTA", "ESTC", "ET", "ET^I", "ETB", "ETD", "ETG", "ETHB", "ETHM",
        "ETHMU", "ETHMW", "ETI^", "ETJ", "ETN", "ETO", "ETON", "ETOR", "ETR", "ETS",
        "ETSY", "ETV", "ETW", "ETX", "ETY", "EU", "EUDA", "EUDAW", "EVAC", "EVAX",
        "EVC", "EVCM", "EVER", "EVEX", "EVF", "EVG", "EVGN", "EVGO", "EVGOW", "EVH",
        "EVI", "EVLV", "EVLVW", "EVMN", "EVN", "EVO", "EVOX", "EVOXU", "EVOXW", "EVR",
        "EVRG", "EVT", "EVTC", "EVTL", "EVTV", "EVV", "EW", "EWBC", "EWCZ", "EWTX",
        "EXC", "EXE", "EXEL", "EXFY", "EXG", "EXK", "EXLS", "EXOD", "EXOZ", "EXP",
        "EXPD", "EXPE", "EXPI", "EXPO", "EXR", "EXTR", "EYE", "EYPT", "EZGO", "EZPW",
        "EZRA", "F", "F^B", "F^C", "F^D", "FA", "FACT", "FACTU", "FACTW", "FAF",
        "FAMI", "FANG", "FARM", "FAST", "FATE", "FATN", "FAX", "FBGL", "FBIN", "FBIO",
        "FBIOP", "FBIZ", "FBK", "FBLA", "FBLG", "FBNC", "FBP", "FBRT", "FBRT^E", "FBRX",
        "FBYD", "FBYDW", "FC", "FCAP", "FCBC", "FCCO", "FCEL", "FCF", "FCFS", "FCHL",
        "FCN", "FCNCA", "FCNCN", "FCNCO", "FCNCP", "FCO", "FCPT", "FCRS", "FCRX", "FCT",
        "FCUV", "FCX", "FDBC", "FDMT", "FDP", "FDS", "FDSB", "FDUS", "FDX", "FE",
        "FEAM", "FEBO", "FEDU", "FEED", "FEIM", "FELE", "FEMY", "FENC", "FENG", "FER",
        "FERA", "FERAR", "FERG", "FET", "FF", "FFA", "FFAI", "FFAIW", "FFBC", "FFC",
        "FFIC", "FFIN", "FFIV", "FG", "FGBI", "FGBIP", "FGI", "FGII", "FGIIU", "FGIIW",
        "FGIWW", "FGL", "FGMC", "FGMCR", "FGN", "FGNX", "FGNXP", "FGSN", "FHB", "FHI",
        "FHN", "FHN^C", "FHN^E", "FHN^F", "FHN^H", "FHTX", "FIBK", "FICO", "FIEE", "FIG",
        "FIGR", "FIGS", "FIGX", "FIHL", "FINS", "FINV", "FINW", "FIP", "FIS", "FISI",
        "FISV", "FITB", "FITBI", "FITBM", "FITBO", "FITBP", "FIVE", "FIVN", "FIX", "FIZZ",
        "FJET", "FKWL", "FLC", "FLD", "FLDDW", "FLEX", "FLG", "FLG^A", "FLG^U", "FLGT",
        "FLL", "FLNA", "FLNC", "FLNG", "FLNT", "FLO", "FLOC", "FLR", "FLS", "FLUT",
        "FLUX", "FLWS", "FLX", "FLXS", "FLY", "FLYE", "FLYW", "FLYX", "FMACU", "FMAO",
        "FMBH", "FMC", "FMFC", "FMN", "FMNB", "FMS", "FMST", "FMSTW", "FMX", "FMY",
        "FN", "FNB", "FND", "FNF", "FNGR", "FNKO", "FNLC", "FNRN", "FNUC", "FNV",
        "FNWB", "FNWD", "FOA", "FOF", "FOFO", "FOLD", "FONR", "FOR", "FORA", "FORM",
        "FORR", "FORTY", "FOSL", "FOUR", "FOUR^A", "FOX", "FOXA", "FOXF", "FOXX", "FOXXW",
        "FPF", "FPH", "FPI", "FPS", "FR", "FRA", "FRAF", "FRBA", "FRD", "FRGT",
        "FRHC", "FRME", "FRMEP", "FRMI", "FRMM", "FRO", "FROG", "FRPH", "FRPT", "FRSH",
        "FRST", "FRSX", "FRT", "FRT^C", "FSBC", "FSBW", "FSCO", "FSEA", "FSHP", "FSI",
        "FSK", "FSLR", "FSLY", "FSM", "FSP", "FSS", "FSSL", "FSTR", "FSUN", "FSV",
        "FT", "FTAI", "FTAIM", "FTAIN", "FTCI", "FTDR", "FTEK", "FTF", "FTFT", "FTHM",
        "FTHY", "FTI", "FTK", "FTLF", "FTNT", "FTRE", "FTRK", "FTS", "FTV", "FTW",
        "FUBO", "FUFU", "FUFUW", "FUL", "FULC", "FULT", "FULTP", "FUN", "FUNC", "FUND",
        "FURY", "FUSB", "FUSE", "FUSEW", "FUTU", "FVAV", "FVCB", "FVN", "FVR", "FVRR",
        "FWDI", "FWONA", "FWONK", "FWRD", "FWRG", "FXNC", "G", "GAB", "GAB^G", "GAB^H",
        "GAB^K", "GABC", "GAIA", "GAIN", "GAING", "GAINI", "GAINN", "GAINZ", "GALT", "GAM",
        "GAM^B", "GAMB", "GAME", "GANX", "GAP", "GASS", "GATX", "GAU", "GAUZ", "GAVA",
        "GBAB", "GBCI", "GBDC", "GBFH", "GBLI", "GBR", "GBTG", "GBX", "GCBC", "GCDT",
        "GCL", "GCMG", "GCO", "GCT", "GCTK", "GCTS", "GCV", "GD", "GDC", "GDDY",
        "GDEN", "GDEV", "GDHG", "GDL", "GDO", "GDOT", "GDRX", "GDS", "GDTC", "GDV",
        "GDV^H", "GDV^K", "GDYN", "GE", "GECC", "GECCG", "GECCH", "GECCI", "GECCO", "GEF",
        "GEG", "GEGGL", "GEHC", "GEL", "GELS", "GEMI", "GEN", "GENB", "GENC", "GENI",
        "GENK", "GENVR", "GEO", "GEOS", "GERN", "GETY", "GEV", "GEVO", "GF", "GFAI",
        "GFAIW", "GFF", "GFI", "GFL", "GFR", "GFS", "GGAL", "GGB", "GGG", "GGN",
        "GGN^B", "GGR", "GGROW", "GGRP", "GGT", "GGT^E", "GGT^G", "GGZ", "GH", "GHC",
        "GHG", "GHI", "GHM", "GHRS", "GHY", "GIB", "GIBO", "GIC", "GIFT", "GIG",
        "GIGGU", "GIGGW", "GIGM", "GIII", "GIL", "GILD", "GILT", "GIPR", "GIPRW", "GIS",
        "GITS", "GIW", "GIWWR", "GIWWU", "GIX", "GIXXR", "GIXXU", "GJH", "GJO", "GJP",
        "GJR", "GJS", "GJT", "GKOS", "GL", "GL^D", "GLAD", "GLBE", "GLBS", "GLDG",
        "GLE", "GLED", "GLIBA", "GLIBK", "GLMD", "GLND", "GLNG", "GLO", "GLOB", "GLOO",
        "GLOP^A", "GLOP^B", "GLOP^C", "GLP", "GLP^B", "GLPG", "GLPI", "GLQ", "GLRE", "GLSI",
        "GLU", "GLU^B", "GLUE", "GLV", "GLW", "GLXG", "GLXY", "GM", "GMAB", "GME",
        "GMED", "GMEX", "GMHS", "GMM", "GMTL", "GNE", "GNK", "GNL", "GNL^A", "GNL^B",
        "GNL^D", "GNL^E", "GNLN", "GNLX", "GNPX", "GNRC", "GNS", "GNSS", "GNT", "GNT^A",
        "GNTA", "GNTX", "GNW", "GO", "GOAI", "GOCO", "GOF", "GOGO", "GOLD", "GOLF",
        "GOOD", "GOODN", "GOODO", "GOOG", "GOOGL", "GOOS", "GORO", "GOSS", "GOTU", "GOVX",
        "GP", "GPAC", "GPACU", "GPAT", "GPATU", "GPATW", "GPC", "GPCR", "GPGI", "GPI",
        "GPJA", "GPK", "GPMT", "GPMT^A", "GPN", "GPOR", "GPRE", "GPRK", "GPRO", "GPUS",
        "GPUS^D", "GRAB", "GRABW", "GRAF", "GRAL", "GRAN", "GRBK", "GRBK^A", "GRC", "GRCE",
        "GRDN", "GRDX", "GREE", "GREEL", "GRF", "GRFS", "GRI", "GRML", "GRMLW", "GRMN",
        "GRND", "GRNQ", "GRNT", "GRO", "GROV", "GROW", "GROY", "GRPN", "GRRR", "GRRRW",
        "GRVY", "GRWG", "GRX", "GS", "GS^A", "GS^C", "GS^D", "GSAT", "GSBC", "GSBD",
        "GSHD", "GSHR", "GSHRW", "GSIT", "GSIW", "GSK", "GSL", "GSL^B", "GSM", "GSRF",
        "GSRFR", "GSUN", "GT", "GTBP", "GTE", "GTEC", "GTEN", "GTENW", "GTERA", "GTERR",
        "GTERU", "GTES", "GTIM", "GTLB", "GTLS", "GTM", "GTN", "GTX", "GTY", "GUG",
        "GURE", "GUT", "GUT^C", "GUTS", "GV", "GVA", "GVH", "GWAV", "GWH", "GWRE",
        "GWRS", "GWW", "GXAI", "GXO", "GYRE", "GYRO", "H", "HACQU", "HAE", "HAFC",
        "HAFN", "HAIN", "HAL", "HALO", "HAO", "HAS", "HASI", "HAVA", "HAVAU", "HAYW",
        "HBAN", "HBANL", "HBANM", "HBANP", "HBANZ", "HBB", "HBCP", "HBIO", "HBM", "HBNB",
        "HBNC", "HBT", "HCA", "HCAC", "HCACR", "HCACU", "HCAI", "HCAT", "HCC", "HCHL",
        "HCI", "HCIC", "HCICR", "HCICU", "HCKT", "HCM", "HCMA", "HCMAU", "HCMAW", "HCSG",
        "HCTI", "HCWB", "HCWC", "HCXY", "HD", "HDB", "HDL", "HDSN", "HE", "HEI",
        "HEI/A", "HELE", "HELP", "HEPS", "HEQ", "HERE", "HERZ", "HESM", "HFBL", "HFFG",
        "HFRO", "HFRO^A", "HFRO^B", "HFWA", "HG", "HGBL", "HGLB", "HGTY", "HGV", "HHH",
        "HHS", "HIFS", "HIG", "HIG^G", "HIHO", "HII", "HIMS", "HIMX", "HIND", "HIO",
        "HIPO", "HIT", "HITI", "HIVE", "HIW", "HIX", "HKD", "HKIT", "HKPD", "HL",
        "HL^B", "HLF", "HLI", "HLIO", "HLIT", "HLLY", "HLMN", "HLN", "HLNE", "HLP",
        "HLT", "HLX", "HLXC", "HMC", "HMH", "HMN", "HMR", "HMY", "HNGE", "HNI",
        "HNNA", "HNNAZ", "HNRG", "HNST", "HNVR", "HOFT", "HOG", "HOLO", "HOLOW", "HOMB",
        "HON", "HOOD", "HOPE", "HOTH", "HOUR", "HOV", "HOVNP", "HOVR", "HOVRW", "HOWL",
        "HP", "HPAI", "HPAIW", "HPE", "HPE^C", "HPF", "HPI", "HPK", "HPP", "HPP^C",
        "HPQ", "HPS", "HQ", "HQH", "HQI", "HQL", "HQWWW", "HQY", "HR", "HRB",
        "HRI", "HRL", "HRMY", "HROW", "HRTG", "HRTX", "HRZN", "HSAI", "HSBC", "HSCS",
        "HSCSW", "HSDT", "HSHP", "HSIC", "HSLV", "HSPT", "HSPTR", "HST", "HSTM", "HSY",
        "HTB", "HTCO", "HTCR", "HTD", "HTFC", "HTFL", "HTGC", "HTH", "HTHT", "HTLD",
        "HTLM", "HTO", "HTOO", "HTT", "HTZ", "HTZWW", "HUBB", "HUBC", "HUBCW", "HUBCZ",
        "HUBG", "HUBS", "HUDI", "HUHU", "HUIZ", "HUM", "HUMA", "HUMAW", "HUN", "HURA",
        "HURC", "HURN", "HUT", "HUYA", "HVII", "HVIIR", "HVIIU", "HVMC", "HVMCU", "HVMCW",
        "HVT", "HVT/A", "HWBK", "HWC", "HWCPZ", "HWH", "HWKN", "HWM", "HXHX", "HXL",
        "HY", "HYFM", "HYFT", "HYI", "HYLN", "HYMC", "HYNE", "HYPD", "HYPR", "HYT",
        "HZO", "IAC", "IACO", "IACOU", "IAE", "IAF", "IAG", "IART", "IAUX", "IBAC",
        "IBACR", "IBCP", "IBEX", "IBG", "IBIO", "IBKR", "IBM", "IBN", "IBO", "IBOC",
        "IBP", "IBRX", "IBTA", "ICCC", "ICCM", "ICE", "ICFI", "ICG", "ICHR", "ICL",
        "ICLR", "ICMB", "ICON", "ICR^A", "ICU", "ICUCW", "ICUI", "IDA", "IDAI", "IDCC",
        "IDE", "IDN", "IDR", "IDT", "IDXX", "IDYA", "IE", "IEAG", "IEAGU", "IEP",
        "IESC", "IEX", "IFBD", "IFF", "IFN", "IFRX", "IFS", "IGA", "IGAC", "IGACR",
        "IGACU", "IGC", "IGD", "IGI", "IGIC", "IGR", "IH", "IHD", "IHG", "IHRT",
        "IHS", "IHT", "IIF", "III", "IIIN", "IIIV", "IIM", "IINN", "IINNW", "IIPR",
        "IIPR^A", "IKT", "ILAG", "ILLR", "ILLRW", "ILLU", "ILLUW", "ILMN", "ILPT", "IMA",
        "IMAX", "IMCC", "IMCR", "IMDX", "IMKTA", "IMMP", "IMMR", "IMMX", "IMNM", "IMNN",
        "IMO", "IMOS", "IMPP", "IMPPP", "IMRN", "IMRX", "IMSR", "IMSRW", "IMTE", "IMTX",
        "IMUX", "IMVT", "IMXI", "INAB", "INAC", "INACR", "INACU", "INBK", "INBKZ", "INBS",
        "INBX", "INCR", "INCY", "INDB", "INDI", "INDO", "INDP", "INDV", "INEO", "INFQ",
        "INFU", "INFY", "ING", "INGM", "INGN", "INGR", "INHD", "INKT", "INLF", "INLX",
        "INM", "INMB", "INMD", "INN", "INN^E", "INN^F", "INNV", "INO", "INOD", "INR",
        "INSE", "INSG", "INSM", "INSP", "INSW", "INTA", "INTC", "INTG", "INTJ", "INTR",
        "INTS", "INTT", "INTU", "INTZ", "INUV", "INV", "INVA", "INVE", "INVH", "INVX",
        "INVZ", "IONQ", "IONR", "IONS", "IOR", "IOSP", "IOT", "IOTR", "IOVA", "IP",
        "IPAR", "IPCX", "IPCXR", "IPCXU", "IPDN", "IPEX", "IPEXR", "IPEXU", "IPFXU", "IPGP",
        "IPHA", "IPI", "IPM", "IPOD", "IPODU", "IPODW", "IPSC", "IPST", "IPW", "IPWR",
        "IPX", "IQ", "IQI", "IQST", "IQV", "IR", "IRD", "IRDM", "IREN", "IRHO",
        "IRHOR", "IRHOU", "IRIX", "IRM", "IRMD", "IRON", "IRS", "IRT", "IRTC", "IRWD",
        "ISBA", "ISD", "ISOU", "ISPC", "ISPR", "ISRG", "ISSC", "ISTR", "IT", "ITGR",
        "ITHAU", "ITIC", "ITOC", "ITP", "ITRG", "ITRI", "ITRN", "ITT", "ITUB", "ITW",
        "IVA", "IVDA", "IVDAW", "IVF", "IVR", "IVR^C", "IVT", "IVVD", "IVZ", "IX",
        "IXHL", "IZEA", "IZM", "J", "JACK", "JACS", "JAGU", "JAGX", "JAKK", "JAN",
        "JANX", "JATT", "JAZZ", "JBDI", "JBGS", "JBHT", "JBI", "JBIO", "JBL", "JBLU",
        "JBS", "JBSS", "JBTM", "JCAP", "JCE", "JCI", "JCSE", "JCTC", "JD", "JDZG",
        "JEF", "JELD", "JEM", "JENA", "JF", "JFB", "JFIN", "JFR", "JFU", "JG",
        "JGH", "JHG", "JHI", "JHS", "JHX", "JILL", "JJSF", "JKHY", "JKS", "JL",
        "JLHL", "JLL", "JLS", "JMIA", "JMM", "JMSB", "JNJ", "JOB", "JOBY", "JOE",
        "JOF", "JOUT", "JOYY", "JPC", "JPM", "JPM^C", "JPM^D", "JPM^J", "JPM^K", "JPM^L",
        "JPM^M", "JQC", "JRI", "JRS", "JRSH", "JRVR", "JSM", "JSPR", "JSPRW", "JTAI",
        "JUNS", "JVA", "JWEL", "JXG", "JXN", "JXN^A", "JYD", "JYNT", "JZ", "JZXN",
        "KAI", "KALA", "KALU", "KALV", "KAPA", "KARO", "KB", "KBDC", "KBH", "KBON",
        "KBONU", "KBONW", "KBR", "KBSX", "KC", "KCHV", "KCHVR", "KD", "KDK", "KDKRW",
        "KDP", "KE", "KEEL", "KELYA", "KELYB", "KEN", "KEP", "KEQU", "KEX", "KEY",
        "KEY^I", "KEY^J", "KEY^K", "KEY^L", "KEYS", "KF", "KFFB", "KFII", "KFIIR", "KFRC",
        "KFS", "KFY", "KG", "KGC", "KGEI", "KGS", "KHC", "KIDS", "KIDZ", "KIDZW",
        "KIM", "KIM^L", "KIM^M", "KIM^N", "KINS", "KIO", "KITT", "KITTW", "KKR", "KKR^D",
        "KKRS", "KKRT", "KLAC", "KLAR", "KLC", "KLIC", "KLRA", "KLRS", "KLTR", "KLXE",
        "KMB", "KMDA", "KMI", "KMPB", "KMPR", "KMRK", "KMT", "KMTS", "KMX", "KN",
        "KNDI", "KNF", "KNOP", "KNRX", "KNSA", "KNSL", "KNTK", "KNX", "KO", "KOD",
        "KODK", "KOF", "KOP", "KOPN", "KORE", "KOS", "KOSS", "KOYN", "KOYNU", "KOYNW",
        "KPLT", "KPLTW", "KPRX", "KPTI", "KR", "KRAQ", "KRAQU", "KRAQW", "KRC", "KREF",
        "KREF^A", "KRG", "KRKR", "KRMD", "KRMN", "KRNT", "KRNY", "KRO", "KROS", "KRP",
        "KRRO", "KRSP", "KRT", "KRUS", "KRYS", "KSCP", "KSPI", "KSS", "KT", "KTB",
        "KTCC", "KTF", "KTH", "KTN", "KTOS", "KTTA", "KTTAW", "KTWO", "KTWOR", "KTWOU",
        "KULR", "KURA", "KUST", "KVAC", "KVACW", "KVHI", "KVUE", "KVYO", "KW", "KWM",
        "KWMWW", "KWR", "KXIN", "KYIV", "KYIVW", "KYMR", "KYN", "KYNB", "KYTX", "KZIA",
        "KZR", "L", "LAB", "LABT", "LAC", "LAD", "LADR", "LAES", "LAFA", "LAKE",
        "LAMR", "LAND", "LANDO", "LANDP", "LANV", "LAR", "LARK", "LASE", "LASR", "LATA",
        "LATAU", "LAUR", "LAW", "LAZ", "LB", "LBGJ", "LBRDA", "LBRDK", "LBRDP", "LBRT",
        "LBRX", "LBTYA", "LBTYB", "LBTYK", "LC", "LCCC", "LCCCU", "LCFY", "LCFYW", "LCID",
        "LCII", "LCNB", "LCTX", "LCUT", "LDI", "LDOS", "LDP", "LE", "LEA", "LECO",
        "LEDS", "LEE", "LEG", "LEGH", "LEGN", "LEGO", "LEGT", "LEN", "LENZ", "LEO",
        "LESL", "LEU", "LEVI", "LEXX", "LFAC", "LFACU", "LFCR", "LFMD", "LFMDP", "LFS",
        "LFST", "LFT", "LFT^A", "LFUS", "LFVN", "LFWD", "LGCB", "LGCL", "LGCY", "LGHL",
        "LGI", "LGIH", "LGL", "LGN", "LGND", "LGO", "LGPS", "LGVN", "LH", "LHAI",
        "LHSW", "LHX", "LI", "LICN", "LIDR", "LIDRW", "LIEN", "LIF", "LIFE", "LII",
        "LILA", "LILAK", "LIMN", "LIMNW", "LIN", "LINC", "LIND", "LINE", "LINK", "LION",
        "LIQT", "LITB", "LITE", "LITS", "LIVE", "LIVN", "LIXT", "LKFN", "LKQ", "LKSP",
        "LKSPR", "LKSPU", "LLY", "LLYVA", "LLYVK", "LMAT", "LMB", "LMFA", "LMND", "LMNR",
        "LMRI", "LMT", "LNAI", "LNC", "LNC^D", "LND", "LNG", "LNKB", "LNKS", "LNN",
        "LNSR", "LNT", "LNTH", "LNZA", "LNZAW", "LOAN", "LOAR", "LOB", "LOB^A", "LOBO",
        "LOCL", "LOCO", "LODE", "LOGI", "LOKV", "LOKVW", "LOMA", "LONA", "LOOP", "LOPE",
        "LOT", "LOTWW", "LOVE", "LOW", "LPA", "LPAA", "LPAAW", "LPBB", "LPBBW", "LPCN",
        "LPCV", "LPCVU", "LPG", "LPL", "LPLA", "LPRO", "LPSN", "LPTH", "LPX", "LQDA",
        "LQDT", "LRCX", "LRE", "LRHC", "LRMR", "LRN", "LSAK", "LSBK", "LSCC", "LSE",
        "LSF", "LSH", "LSPD", "LSTA", "LSTR", "LTBR", "LTC", "LTH", "LTM", "LTRN",
        "LTRX", "LTRYW", "LU", "LUCD", "LUCK", "LUCY", "LUCYW", "LUD", "LULU", "LUMN",
        "LUNG", "LUNR", "LUV", "LUXE", "LVLU", "LVO", "LVS", "LVWR", "LW", "LWAC",
        "LWACW", "LWAY", "LWLG", "LX", "LXEH", "LXEO", "LXFR", "LXP", "LXP^C", "LXRX",
        "LXU", "LYB", "LYEL", "LYFT", "LYG", "LYTS", "LYV", "LZ", "LZB", "LZM",
        "LZMH", "M", "MA", "MAA", "MAA^I", "MAAS", "MAC", "MACI", "MAGN", "MAIA",
        "MAIN", "MAIR", "MAKO", "MAMA", "MAMO", "MAN", "MANE", "MANH", "MANU", "MAPS",
        "MAPSW", "MAR", "MARA", "MARPS", "MAS", "MASI", "MASK", "MASS", "MAT", "MATH",
        "MATV", "MATW", "MATX", "MAX", "MAXN", "MAYS", "MAZE", "MB", "MBAI", "MBAV",
        "MBAVW", "MBBC", "MBC", "MBI", "MBIN", "MBINL", "MBINM", "MBINN", "MBIO", "MBLY",
        "MBNKO", "MBOT", "MBRX", "MBUU", "MBVI", "MBVIU", "MBVIW", "MBWM", "MBX", "MC",
        "MCB", "MCBS", "MCD", "MCFT", "MCGA", "MCGAU", "MCGAW", "MCHB", "MCHP", "MCHPP",
        "MCHX", "MCI", "MCK", "MCN", "MCO", "MCR", "MCRB", "MCRI", "MCRP", "MCS",
        "MCW", "MCY", "MD", "MDA", "MDAI", "MDAIW", "MDB", "MDBH", "MDCX", "MDCXW",
        "MDGL", "MDIA", "MDLN", "MDLZ", "MDRR", "MDT", "MDU", "MDV", "MDV^A", "MDWD",
        "MDXG", "MDXH", "MEC", "MED", "MEDP", "MEG", "MEGI", "MEGL", "MEHA", "MEI",
        "MELI", "MENS", "MEOH", "MER^K", "MERC", "MESH", "MESHU", "MESO", "MET", "MET^A",
        "MET^E", "MET^F", "META", "METC", "METCB", "METCI", "METCZ", "MEVO", "MEVOU", "MEVOW",
        "MFA", "MFA^B", "MFA^C", "MFAN", "MFAO", "MFC", "MFG", "MFI", "MFIC", "MFICL",
        "MFIN", "MFM", "MG", "MGA", "MGEE", "MGF", "MGIH", "MGLD", "MGM", "MGN",
        "MGNI", "MGNX", "MGPI", "MGR", "MGRB", "MGRC", "MGRD", "MGRE", "MGRT", "MGRX",
        "MGTX", "MGX", "MGY", "MGYR", "MH", "MHD", "MHF", "MHH", "MHK", "MHLA",
        "MHNC", "MHO", "MI", "MIAX", "MICC", "MIDD", "MIGI", "MIMI", "MIN", "MIND",
        "MINE", "MIR", "MIRA", "MIRM", "MIST", "MITK", "MITN", "MITP", "MITQ", "MITT",
        "MITT^A", "MITT^B", "MITT^C", "MIY", "MKC", "MKDW", "MKDWW", "MKL", "MKLY", "MKLYR",
        "MKLYU", "MKSI", "MKTW", "MKTX", "MKZR", "MLAA", "MLAAU", "MLAAW", "MLAB", "MLAC",
        "MLACU", "MLCI", "MLCIL", "MLCO", "MLEC", "MLECW", "MLGO", "MLI", "MLKN", "MLM",
        "MLP", "MLR", "MLSS", "MLTX", "MLYS", "MMA", "MMD", "MMED", "MMI", "MMLP",
        "MMM", "MMS", "MMSI", "MMT", "MMTX", "MMU", "MMYT", "MNDO", "MNDR", "MNDY",
        "MNKD", "MNOV", "MNPR", "MNR", "MNRO", "MNSB", "MNSBP", "MNSO", "MNST", "MNTK",
        "MNTN", "MNTS", "MNTSW", "MNY", "MNYWW", "MO", "MOB", "MOBBW", "MOBX", "MOBXW",
        "MOD", "MODD", "MOGU", "MOH", "MOLN", "MOMO", "MORN", "MOS", "MOV", "MOVE",
        "MP", "MPA", "MPAA", "MPB", "MPC", "MPLT", "MPLX", "MPT", "MPTI", "MPU",
        "MPV", "MPWR", "MPX", "MQ", "MQY", "MRAM", "MRBK", "MRCY", "MRDN", "MREO",
        "MRK", "MRKR", "MRLN", "MRM", "MRNA", "MRNO", "MRNOW", "MRP", "MRSH", "MRT",
        "MRTN", "MRVI", "MRVL", "MRX", "MS", "MS^A", "MS^E", "MS^F", "MS^I", "MS^K",
        "MS^L", "MS^O", "MS^P", "MS^Q", "MSA", "MSAI", "MSAIW", "MSB", "MSBI", "MSBIP",
        "MSC", "MSCI", "MSD", "MSDL", "MSEX", "MSFT", "MSGE", "MSGM", "MSGS", "MSGY",
        "MSI", "MSIF", "MSLE", "MSM", "MSN", "MSS", "MSTR", "MSW", "MT", "MTA",
        "MTAL", "MTB", "MTB^H", "MTB^J", "MTB^K", "MTC", "MTCH", "MTD", "MTDR", "MTEK",
        "MTEKW", "MTEN", "MTEX", "MTG", "MTH", "MTLS", "MTN", "MTNB", "MTR", "MTRN",
        "MTRX", "MTSI", "MTUS", "MTVA", "MTW", "MTX", "MTZ", "MU", "MUA", "MUC",
        "MUFG", "MUJ", "MUR", "MUSA", "MUX", "MUZE", "MUZEU", "MUZEW", "MVBF", "MVIS",
        "MVO", "MVST", "MVSTW", "MWA", "MWG", "MWH", "MWYN", "MX", "MXC", "MXCT",
        "MXE", "MXF", "MXL", "MYE", "MYFW", "MYGN", "MYI", "MYN", "MYND", "MYO",
        "MYPS", "MYPSW", "MYRG", "MYSE", "MYSEW", "MYSZ", "MYXXU", "MZTI", "NAAS", "NABL",
        "NAC", "NAD", "NAGE", "NAII", "NAK", "NAKA", "NAMI", "NAMM", "NAMMW", "NAMS",
        "NAMSW", "NAN", "NAT", "NATH", "NATL", "NATR", "NAUT", "NAVI", "NAVN", "NAZ",
        "NB", "NBB", "NBBK", "NBH", "NBHC", "NBIS", "NBIX", "NBN", "NBP", "NBR",
        "NBRGR", "NBRGU", "NBTB", "NBTX", "NBXG", "NC", "NCA", "NCDL", "NCEL", "NCEW",
        "NCI", "NCL", "NCLH", "NCMI", "NCNA", "NCNO", "NCPL", "NCPLW", "NCRA", "NCSM",
        "NCT", "NCTY", "NCV", "NCV^A", "NCZ", "NCZ^A", "NDAQ", "NDLS", "NDMO", "NDRA",
        "NDSN", "NE", "NEA", "NECB", "NEE", "NEE^N", "NEE^S", "NEE^T", "NEE^U", "NEE^V",
        "NEE^W", "NEGG", "NEM", "NEN", "NEO", "NEOG", "NEON", "NEOV", "NEOVW", "NEPH",
        "NERV", "NESR", "NET", "NEU", "NEUP", "NEWP", "NEWT", "NEWTG", "NEWTH", "NEWTI",
        "NEWTO", "NEWTP", "NEXA", "NEXM", "NEXN", "NEXR", "NEXRW", "NEXT", "NFBK", "NFE",
        "NFG", "NFGC", "NFJ", "NFLX", "NG", "NGEN", "NGG", "NGL", "NGL^B", "NGL^C",
        "NGNE", "NGS", "NGVC", "NGVT", "NHC", "NHI", "NHIC", "NHICU", "NHICW", "NHIVU",
        "NHP", "NHPAP", "NHPBP", "NHS", "NHTC", "NI", "NIC", "NICE", "NICM", "NIE",
        "NIM", "NINE", "NIO", "NIOBW", "NIPG", "NIQ", "NIU", "NIVF", "NIVFW", "NIXX",
        "NIXXW", "NJR", "NKE", "NKLR", "NKSH", "NKTR", "NKTX", "NKX", "NL", "NLOP",
        "NLY", "NLY^F", "NLY^G", "NLY^I", "NLY^J", "NMAI", "NMAX", "NMCO", "NMFC", "NMFCZ",
        "NMG", "NMI", "NMIH", "NML", "NMM", "NMP", "NMPAR", "NMPAU", "NMR", "NMRA",
        "NMRK", "NMS", "NMT", "NMTC", "NMZ", "NN", "NNAVW", "NNBR", "NNDM", "NNE",
        "NNI", "NNN", "NNNN", "NNOX", "NNVC", "NNY", "NOA", "NOAH", "NOC", "NODK",
        "NOEM", "NOEMR", "NOEMU", "NOEMW", "NOG", "NOK", "NOM", "NOMA", "NOMD", "NOTV",
        "NOV", "NOVT", "NOVTU", "NOW", "NP", "NPAC", "NPACU", "NPACW", "NPB", "NPCE",
        "NPCT", "NPFD", "NPK", "NPKI", "NPO", "NPT", "NPV", "NPWR", "NQP", "NRC",
        "NRDS", "NRDY", "NREF", "NREF^A", "NRG", "NRGV", "NRIM", "NRIX", "NRK", "NRO",
        "NRP", "NRSN", "NRSNW", "NRT", "NRUC", "NRXP", "NRXPW", "NRXS", "NSA", "NSA^A",
        "NSA^B", "NSC", "NSIT", "NSP", "NSPR", "NSRX", "NSSC", "NSTS", "NSYS", "NTAP",
        "NTB", "NTCL", "NTCT", "NTES", "NTGR", "NTHI", "NTIC", "NTIP", "NTLA", "NTNX",
        "NTR", "NTRA", "NTRB", "NTRBW", "NTRP", "NTRS", "NTRSO", "NTSK", "NTST", "NTWK",
        "NTWO", "NTWOW", "NTZ", "NU", "NUAI", "NUAIW", "NUCL", "NUCLW", "NUE", "NUS",
        "NUTX", "NUV", "NUVB", "NUVL", "NUW", "NUWE", "NVA", "NVAWW", "NVAX", "NVCR",
        "NVCT", "NVDA", "NVEC", "NVG", "NVGS", "NVMI", "NVNI", "NVNIW", "NVNO", "NVO",
        "NVR", "NVRI", "NVS", "NVST", "NVT", "NVTS", "NVVE", "NVX", "NWAX", "NWBI",
        "NWE", "NWFL", "NWG", "NWGL", "NWL", "NWN", "NWPX", "NWS", "NWSA", "NWTG",
        "NX", "NXDR", "NXDT", "NXDT^A", "NXE", "NXG", "NXGL", "NXGLW", "NXJ", "NXL",
        "NXP", "NXPI", "NXPL", "NXPLW", "NXRT", "NXST", "NXT", "NXTC", "NXTS", "NXTT",
        "NXXT", "NYAX", "NYC", "NYT", "NYXH", "NZF", "O", "OABI", "OABIW", "OACC",
        "OACCU", "OACCW", "OAK^A", "OAK^B", "OBA", "OBAI", "OBAWU", "OBDC", "OBE", "OBIO",
        "OBK", "OBT", "OBTC", "OC", "OCC", "OCCI", "OCCIM", "OCCIN", "OCCIO", "OCFC",
        "OCG", "OCGN", "OCS", "OCSAW", "OCSL", "OCUL", "ODC", "ODD", "ODFL", "ODV",
        "ODVWZ", "ODYS", "OEC", "OESX", "OFAL", "OFG", "OFIX", "OFLX", "OFRM", "OFS",
        "OFSSH", "OFSSO", "OGC", "OGE", "OGEN", "OGI", "OGN", "OGS", "OHI", "OI",
        "OIA", "OII", "OIM", "OIMAU", "OIMAW", "OIO", "OIOWW", "OIS", "OKE", "OKLO",
        "OKTA", "OKUR", "OKYO", "OLB", "OLED", "OLLI", "OLMA", "OLN", "OLOX", "OLP",
        "OLPX", "OM", "OMAB", "OMC", "OMCL", "OMDA", "OMER", "OMEX", "OMF", "OMH",
        "OMSE", "ON", "ONB", "ONBPO", "ONBPP", "ONC", "ONCH", "ONCHU", "ONCO", "ONCY",
        "ONDS", "ONEG", "ONEW", "ONFO", "ONFOW", "ONIT", "ONL", "ONMD", "ONMDW", "ONON",
        "ONTO", "OOMA", "OPAD", "OPAL", "OPBK", "OPCH", "OPEN", "OPENL", "OPENW", "OPENZ",
        "OPFI", "OPHC", "OPK", "OPLN", "OPP", "OPP^A", "OPP^B", "OPP^C", "OPRA", "OPRT",
        "OPRX", "OPTT", "OPTU", "OPTX", "OPTXW", "OPXS", "OPY", "OR", "ORA", "ORBS",
        "ORC", "ORCL", "ORCL^D", "ORGN", "ORGNW", "ORGO", "ORI", "ORIC", "ORIO", "ORIQ",
        "ORIQW", "ORIS", "ORKA", "ORKT", "ORLA", "ORLY", "ORMP", "ORN", "ORRF", "OSBC",
        "OSCR", "OSG", "OSIS", "OSK", "OSPN", "OSRH", "OSRHW", "OSS", "OSTX", "OSUR",
        "OSW", "OTEX", "OTF", "OTGA", "OTGAU", "OTGAW", "OTH", "OTIS", "OTLK", "OTLY",
        "OTTR", "OUST", "OUT", "OVBC", "OVID", "OVLY", "OVV", "OWL", "OWLS", "OWLT",
        "OXBR", "OXLC", "OXLCG", "OXLCI", "OXLCL", "OXLCM", "OXLCN", "OXLCO", "OXLCP", "OXLCZ",
        "OXM", "OXSQ", "OXSQG", "OXSQH", "OXY", "OYSE", "OYSER", "OZ", "OZK", "OZKAP",
        "P", "PAA", "PAAC", "PAACU", "PAACW", "PAAS", "PAC", "PACB", "PACH", "PACHW",
        "PACK", "PACS", "PAG", "PAGP", "PAGS", "PAHC", "PAI", "PAII", "PAL", "PALI",
        "PALO", "PALOU", "PALOW", "PAM", "PAMT", "PANL", "PANW", "PAPL", "PAR", "PARK",
        "PARR", "PASG", "PASW", "PATH", "PATK", "PAVM", "PAVS", "PAX", "PAXS", "PAY",
        "PAYC", "PAYO", "PAYP", "PAYS", "PAYX", "PB", "PBA", "PBF", "PBFS", "PBH",
        "PBHC", "PBI", "PBI^B", "PBM", "PBMWW", "PBR", "PBT", "PBYI", "PCAP", "PCAPU",
        "PCAPW", "PCAR", "PCB", "PCF", "PCG", "PCG^A", "PCG^B", "PCG^C", "PCG^D", "PCG^E",
        "PCG^G", "PCG^H", "PCG^I", "PCG^X", "PCLA", "PCM", "PCN", "PCOR", "PCQ", "PCRX",
        "PCSA", "PCSC", "PCT", "PCTTU", "PCTTW", "PCTY", "PCVX", "PCYO", "PD", "PDC",
        "PDCC", "PDD", "PDEX", "PDFS", "PDI", "PDLB", "PDM", "PDO", "PDPA", "PDS",
        "PDSB", "PDT", "PDX", "PDYN", "PDYNW", "PEB", "PEB^E", "PEB^F", "PEB^G", "PEB^H",
        "PEBK", "PEBO", "PECO", "PED", "PEG", "PEGA", "PEN", "PENG", "PENN", "PEO",
        "PEP", "PEPG", "PERF", "PERI", "PESI", "PETS", "PETZ", "PEW", "PFAI", "PFBC",
        "PFD", "PFE", "PFG", "PFGC", "PFH", "PFIS", "PFL", "PFLT", "PFN", "PFO",
        "PFS", "PFSA", "PFSI", "PFX", "PFXNZ", "PG", "PGAC", "PGC", "PGEN", "PGNY",
        "PGP", "PGR", "PGY", "PGYWW", "PGZ", "PH", "PHAR", "PHAT", "PHG", "PHGE",
        "PHI", "PHIN", "PHIO", "PHK", "PHM", "PHOE", "PHR", "PHUN", "PHVS", "PHXE^",
        "PI", "PICS", "PII", "PIII", "PIIIW", "PIM", "PINE", "PINE^A", "PINS", "PIPR",
        "PJT", "PK", "PKBK", "PKE", "PKG", "PKOH", "PKST", "PKX", "PL", "PLAB",
        "PLAG", "PLAY", "PLBC", "PLBL", "PLBY", "PLCE", "PLD", "PLG", "PLMK", "PLMKW",
        "PLMR", "PLNT", "PLOW", "PLPC", "PLRX", "PLRZ", "PLSE", "PLSM", "PLTK", "PLTR",
        "PLUG", "PLUR", "PLUS", "PLUT", "PLX", "PLXS", "PLYX", "PM", "PMAX", "PMCB",
        "PMEC", "PMI", "PML", "PMM", "PMN", "PMNT", "PMO", "PMT", "PMT^A", "PMT^B",
        "PMT^C", "PMTR", "PMTRW", "PMTS", "PMTU", "PMTV", "PMTW", "PMVP", "PN", "PNBK",
        "PNC", "PNFP", "PNFP^A", "PNFP^B", "PNFP^C", "PNI", "PNNT", "PNR", "PNRG", "PNTG",
        "PNW", "POAS", "POCI", "PODC", "PODD", "POET", "POLA", "POLE", "POLEW", "POM",
        "PONOU", "PONY", "POOL", "POR", "POST", "POWI", "POWL", "POWW", "POWWP", "PPBT",
        "PPC", "PPCB", "PPG", "PPHC", "PPIH", "PPL", "PPLC", "PPSI", "PPT", "PPTA",
        "PR", "PRA", "PRAA", "PRAX", "PRCH", "PRCT", "PRDO", "PRE", "PRFX", "PRG",
        "PRGO", "PRGS", "PRH", "PRHI", "PRHIZ", "PRI", "PRIF^D", "PRIF^K", "PRIF^L", "PRIM",
        "PRK", "PRKS", "PRLB", "PRLD", "PRM", "PRMB", "PRME", "PROF", "PROK", "PROP",
        "PROV", "PRPL", "PRPO", "PRQR", "PRS", "PRSO", "PRSU", "PRT", "PRTA", "PRTC",
        "PRTH", "PRTS", "PRU", "PRVA", "PRZO", "PSA", "PSA^F", "PSA^G", "PSA^H", "PSA^I",
        "PSA^J", "PSA^K", "PSA^L", "PSA^M", "PSA^N", "PSA^O", "PSA^P", "PSA^Q", "PSA^R", "PSA^S",
        "PSBD", "PSEC", "PSEC^A", "PSF", "PSFE", "PSHG", "PSIG", "PSIX", "PSKY", "PSMT",
        "PSN", "PSNL", "PSNY", "PSNYW", "PSO", "PSQH", "PSTL", "PSTV", "PSX", "PTA",
        "PTC", "PTCT", "PTEN", "PTGX", "PTHS", "PTLE", "PTLO", "PTN", "PTON", "PTOR",
        "PTORU", "PTORW", "PTRN", "PTY", "PUBM", "PUK", "PULM", "PUMP", "PURR", "PVH",
        "PVL", "PVLA", "PW", "PW^A", "PWP", "PWR", "PXED", "PXLW", "PXS", "PYPD",
        "PYPL", "PYT", "PYXS", "PZG", "PZZA", "Q", "QADRU", "QBTS", "QCLS", "QCOM",
        "QCRH", "QDEL", "QETA", "QETAR", "QFIN", "QGEN", "QLYS", "QMCO", "QNC", "QNCX",
        "QNRX", "QNST", "QNTM", "QQQX", "QRHC", "QRVO", "QS", "QSEA", "QSEAU", "QSI",
        "QSIAW", "QSR", "QTI", "QTRX", "QTTB", "QTWO", "QUAD", "QUBT", "QUCY", "QUIK",
        "QUMS", "QURE", "QXO", "QXO^B", "R", "RA", "RAAQ", "RAAQU", "RAAQW", "RAC",
        "RAC/WS", "RACE", "RADX", "RAIL", "RAIN", "RAINW", "RAL", "RAMP", "RAND", "RANG",
        "RANGR", "RANI", "RAPP", "RARE", "RAVE", "RAY", "RAYA", "RBA", "RBB", "RBBN",
        "RBC", "RBCAA", "RBKB", "RBLX", "RBNE", "RBRK", "RC", "RC^C", "RC^E", "RCAT",
        "RCD", "RCEL", "RCG", "RCI", "RCKT", "RCKTW", "RCKY", "RCL", "RCMT", "RCON",
        "RCS", "RCT", "RCUS", "RDAC", "RDACU", "RDAG", "RDAGU", "RDAGW", "RDCM", "RDDT",
        "RDGT", "RDHL", "RDI", "RDIB", "RDN", "RDNT", "RDNW", "RDVT", "RDW", "RDWR",
        "RDY", "RDZN", "RDZNW", "REAL", "REAX", "REBN", "RECT", "REE", "REED", "REFI",
        "REFR", "REG", "REGCO", "REGCP", "REGN", "REI", "REKR", "RELL", "RELX", "RELY",
        "RENT", "RENX", "REPL", "REPX", "RERE", "RES", "RETO", "REVB", "REVBW", "REX",
        "REXR", "REXR^B", "REXR^C", "REYN", "REZI", "RF", "RF^C", "RF^E", "RF^F", "RFAI",
        "RFAIR", "RFAM", "RFAMU", "RFI", "RFIL", "RFL", "RFM", "RFMZ", "RGA", "RGC",
        "RGCO", "RGEN", "RGLD", "RGNT", "RGNX", "RGP", "RGR", "RGS", "RGT", "RGTI",
        "RGTIW", "RH", "RHI", "RHLD", "RHP", "RIBB", "RICK", "RIG", "RIGL", "RILY",
        "RILYG", "RILYL", "RILYN", "RILYP", "RILYT", "RILYZ", "RIME", "RIO", "RIOT", "RITM",
        "RITM^A", "RITM^B", "RITM^C", "RITM^D", "RITM^E", "RITM^F", "RITR", "RIV", "RIV^A", "RIVN",
        "RJET", "RJF", "RKDA", "RKLB", "RKT", "RL", "RLAY", "RLGT", "RLI", "RLJ",
        "RLJ^A", "RLMD", "RLTY", "RLX", "RLYB", "RM", "RMAX", "RMBI", "RMBS", "RMCF",
        "RMCO", "RMCOW", "RMD", "RMI", "RMIX", "RMM", "RMMZ", "RMNI", "RMR", "RMSG",
        "RMSGW", "RMT", "RMTI", "RNA", "RNAC", "RNAZ", "RNG", "RNGR", "RNGT", "RNGTU",
        "RNGTW", "RNP", "RNR", "RNR^F", "RNR^G", "RNST", "RNTX", "RNW", "RNWWW", "RNXT",
        "ROAD", "ROC", "ROCK", "ROG", "ROIV", "ROK", "ROKU", "ROL", "ROLR", "ROMA",
        "ROOT", "ROP", "ROST", "RPAY", "RPC", "RPD", "RPGL", "RPID", "RPM", "RPRX",
        "RPT", "RPT^C", "RQI", "RR", "RRBI", "RRC", "RRGB", "RRR", "RRX", "RS",
        "RSF", "RSG", "RSI", "RSKD", "RSSS", "RSVR", "RSVRW", "RTAC", "RTACU", "RTACW",
        "RTO", "RTX", "RUBI", "RUM", "RUMBW", "RUN", "RUSHA", "RUSHB", "RVI", "RVLV",
        "RVMD", "RVMDW", "RVP", "RVPH", "RVSB", "RVSN", "RVSNW", "RVT", "RVTY", "RVYL",
        "RWAY", "RWAYI", "RWAYL", "RWT", "RWT^A", "RWTN", "RWTO", "RWTP", "RWTQ", "RXO",
        "RXRX", "RXST", "RXT", "RY", "RYAAY", "RYAM", "RYAN", "RYDE", "RYET", "RYM",
        "RYN", "RYOJ", "RYTM", "RYZ", "RZB", "RZC", "RZLT", "RZLV", "RZLVW", "S",
        "SA", "SAAQ", "SAAQU", "SAAQW", "SABA", "SABR", "SABS", "SABSW", "SAC", "SACH",
        "SACH^A", "SAFE", "SAFT", "SAFX", "SAGT", "SAH", "SAIA", "SAIC", "SAIH", "SAIHW",
        "SAIL", "SAJ", "SAM", "SAMG", "SAN", "SANA", "SANG", "SANM", "SAP", "SAR",
        "SARO", "SAT", "SATA", "SATL", "SATLW", "SATS", "SAV", "SAY", "SAZ", "SB",
        "SB^C", "SB^D", "SBAC", "SBC", "SBCF", "SBCWW", "SBET", "SBEV", "SBFG", "SBFM",
        "SBGI", "SBH", "SBI", "SBLK", "SBLX", "SBR", "SBRA", "SBS", "SBSI", "SBSW",
        "SBUX", "SBXD", "SCAG", "SCAGW", "SCCD", "SCCE", "SCCF", "SCCG", "SCCO", "SCD",
        "SCE^G", "SCE^L", "SCE^M", "SCE^N", "SCHL", "SCHW", "SCHW^D", "SCHW^J", "SCI", "SCII",
        "SCIIR", "SCIIU", "SCKT", "SCL", "SCLX", "SCLXW", "SCM", "SCNI", "SCNX", "SCOR",
        "SCPQ", "SCPQU", "SCPQW", "SCSC", "SCVL", "SCWO", "SCYX", "SCZM", "SD", "SDA",
        "SDAWW", "SDEV", "SDGR", "SDHC", "SDHI", "SDHIU", "SDHY", "SDOT", "SDRL", "SDST",
        "SDSTW", "SE", "SEAL^A", "SEAL^B", "SEAT", "SEATW", "SEB", "SEDG", "SEED", "SEER",
        "SEG", "SEGG", "SEI", "SEIC", "SELF", "SELX", "SEM", "SEMR", "SENEA", "SENEB",
        "SENS", "SEPN", "SER", "SERA", "SERV", "SES", "SEV", "SEVN", "SEZL", "SF",
        "SF^B", "SF^C", "SF^D", "SFB", "SFBC", "SFBS", "SFD", "SFHG", "SFIX", "SFL",
        "SFM", "SFNC", "SFST", "SFWL", "SG", "SGA", "SGC", "SGHC", "SGHT", "SGI",
        "SGLY", "SGML", "SGMO", "SGMT", "SGP", "SGRP", "SGRY", "SGU", "SHAK", "SHAZ",
        "SHBI", "SHC", "SHEL", "SHEN", "SHFS", "SHFSW", "SHG", "SHIM", "SHIP", "SHLS",
        "SHMD", "SHMDW", "SHO", "SHO^H", "SHO^I", "SHOO", "SHOP", "SHPH", "SHW", "SI",
        "SIBN", "SID", "SIDU", "SIEB", "SIF", "SIFY", "SIG", "SIGA", "SIGI", "SIGIP",
        "SII", "SILA", "SILC", "SILO", "SIM", "SIMA", "SIMAW", "SIMO", "SINT", "SION",
        "SIRI", "SITC", "SITE", "SITM", "SJ", "SJM", "SJT", "SKBL", "SKE", "SKIL",
        "SKIN", "SKK", "SKLZ", "SKM", "SKT", "SKWD", "SKY", "SKYE", "SKYH", "SKYQ",
        "SKYT", "SKYW", "SKYX", "SLAB", "SLAI", "SLB", "SLDB", "SLDE", "SLDP", "SLDPW",
        "SLE", "SLF", "SLG", "SLG^I", "SLGB", "SLGL", "SLGN", "SLI", "SLM", "SLMBP",
        "SLMT", "SLN", "SLND", "SLNG", "SLNH", "SLNHP", "SLNO", "SLP", "SLQT", "SLRC",
        "SLS", "SLSN", "SLSR", "SLVM", "SLXN", "SLXNW", "SM", "SMA", "SMBC", "SMBK",
        "SMC", "SMCI", "SMFG", "SMG", "SMHI", "SMID", "SMJF", "SMMT", "SMP", "SMPL",
        "SMR", "SMRT", "SMSI", "SMTC", "SMTI", "SMTK", "SMWB", "SMX", "SMXT", "SMXWW",
        "SN", "SNA", "SNAL", "SNAP", "SNBR", "SNCY", "SND", "SNDA", "SNDK", "SNDL",
        "SNDR", "SNDX", "SNES", "SNEX", "SNFCA", "SNGX", "SNN", "SNOA", "SNOW", "SNPS",
        "SNSE", "SNT", "SNTG", "SNTI", "SNWV", "SNX", "SNY", "SNYR", "SO", "SOAR",
        "SOBO", "SOBR", "SOC", "SOCA", "SOCAU", "SOFI", "SOGP", "SOHU", "SOJC", "SOJD",
        "SOJE", "SOJF", "SOLS", "SOLV", "SOMN", "SON", "SONM", "SONO", "SONY", "SOPA",
        "SOPH", "SOR", "SORA", "SORN", "SOS", "SOTK", "SOUL", "SOUN", "SOUNW", "SOWG",
        "SPAI", "SPB", "SPCB", "SPCE", "SPE", "SPE^C", "SPEG", "SPEGR", "SPEGU", "SPFI",
        "SPG", "SPG^J", "SPGI", "SPH", "SPHL", "SPHR", "SPIR", "SPKL", "SPKLW", "SPMA",
        "SPMC", "SPME", "SPNT", "SPOK", "SPOT", "SPPL", "SPRB", "SPRC", "SPRO", "SPRU",
        "SPRY", "SPSC", "SPT", "SPWH", "SPWR", "SPWRW", "SPXC", "SPXX", "SQFT", "SQFTP",
        "SQFTW", "SQM", "SQNS", "SR", "SRAD", "SRBK", "SRCE", "SRE", "SREA", "SRFM",
        "SRG", "SRG^A", "SRI", "SRJN", "SRL", "SRPT", "SRRK", "SRTA", "SRTAW", "SRTS",
        "SRV", "SRXH", "SRZN", "SSAC", "SSACR", "SSACW", "SSB", "SSBI", "SSD", "SSEA",
        "SSII", "SSL", "SSM", "SSNC", "SSP", "SSRM", "SSSS", "SSSSL", "SST", "SSTI",
        "SSTK", "SSYS", "ST", "STAA", "STAG", "STAK", "STBA", "STC", "STE", "STEL",
        "STEM", "STEP", "STEW", "STEX", "STFS", "STG", "STGW", "STHO", "STI", "STIM",
        "STK", "STKE", "STKH", "STKL", "STKS", "STLA", "STLD", "STM", "STN", "STNE",
        "STNG", "STOK", "STRA", "STRC", "STRD", "STRF", "STRK", "STRL", "STRO", "STRR",
        "STRRP", "STRS", "STRT", "STRW", "STRZ", "STSS", "STSSW", "STT", "STT^G", "STTK",
        "STUB", "STVN", "STWD", "STX", "STXS", "STZ", "SU", "SUGP", "SUI", "SUIG",
        "SUIS", "SUMA", "SUMAR", "SUMAU", "SUN", "SUNB", "SUNC", "SUNE", "SUNS", "SUPN",
        "SUPV", "SUPX", "SURG", "SUUN", "SUZ", "SVAC", "SVACW", "SVAQ", "SVAQU", "SVC",
        "SVCC", "SVCCW", "SVCO", "SVIV", "SVIVU", "SVIVW", "SVM", "SVRA", "SVRE", "SVREW",
        "SVRN", "SVV", "SW", "SWAG", "SWAGW", "SWBI", "SWIM", "SWK", "SWKHL", "SWKS",
        "SWMR", "SWVL", "SWVLW", "SWX", "SWZ", "SXC", "SXI", "SXT", "SXTC", "SXTP",
        "SXTPW", "SY", "SYBT", "SYF", "SYF^A", "SYF^B", "SYK", "SYM", "SYNA", "SYNX",
        "SYPR", "SYRE", "SYY", "SZZL", "SZZLR", "SZZLU", "T", "T^A", "T^C", "TAC",
        "TACH", "TACHW", "TACO", "TACOU", "TACOW", "TACT", "TAK", "TAL", "TALK", "TALKW",
        "TALO", "TANH", "TAOP", "TAOX", "TAP", "TARA", "TARS", "TASK", "TATT", "TAVI",
        "TAVIR", "TAYD", "TBB", "TBBB", "TBBK", "TBCH", "TBH", "TBI", "TBLA", "TBLAW",
        "TBLD", "TBN", "TBPH", "TBRG", "TC", "TCBI", "TCBIO", "TCBK", "TCBS", "TCBX",
        "TCI", "TCMD", "TCOM", "TCPA", "TCPC", "TCRT", "TCRX", "TCX", "TD", "TDAC",
        "TDACW", "TDAY", "TDC", "TDF", "TDG", "TDIC", "TDOC", "TDOG", "TDS", "TDS^U",
        "TDS^V", "TDTH", "TDUP", "TDW", "TDWDR", "TDY", "TE", "TEAD", "TEAM", "TECH",
        "TECK", "TECX", "TEI", "TEL", "TELA", "TELO", "TEM", "TEN", "TEN^E", "TEN^F",
        "TENB", "TENX", "TEO", "TER", "TERN", "TEVA", "TEX", "TFC", "TFC^I", "TFC^O",
        "TFC^R", "TFII", "TFIN", "TFIN^", "TFPM", "TFSL", "TFX", "TG", "TGB", "TGE",
        "TGEN", "TGHL", "TGL", "TGLS", "TGS", "TGT", "TGTX", "TH", "THC", "THCH",
        "THFF", "THG", "THH", "THM", "THO", "THQ", "THR", "THRM", "THRY", "THW",
        "TIC", "TIGO", "TIGR", "TII", "TIL", "TILE", "TIMB", "TIPT", "TISI", "TITN",
        "TIVC", "TJGC", "TJX", "TK", "TKC", "TKLF", "TKNO", "TKO", "TKR", "TLF",
        "TLIH", "TLK", "TLN", "TLNC", "TLNCU", "TLNCW", "TLPH", "TLRY", "TLS", "TLSA",
        "TLSI", "TLSIW", "TLX", "TLYS", "TM", "TMC", "TMCI", "TMCR", "TMCWW", "TMDE",
        "TMDX", "TME", "TMHC", "TMO", "TMP", "TMQ", "TMTS", "TMTSU", "TMUS", "TMUSI",
        "TMUSL", "TMUSZ", "TNC", "TNDM", "TNET", "TNGX", "TNK", "TNL", "TNMG", "TNON",
        "TNXP", "TNYA", "TOI", "TOIIW", "TOL", "TOMZ", "TONX", "TOON", "TOP", "TOPP",
        "TOPS", "TORO", "TOST", "TOUR", "TOVX", "TOWN", "TOYO", "TPB", "TPC", "TPCS",
        "TPET", "TPG", "TPGXL", "TPH", "TPL", "TPR", "TPST", "TPTA", "TPVG", "TR",
        "TRAD", "TRAK", "TRAW", "TRAX", "TRC", "TRDA", "TREE", "TREX", "TRGP", "TRGS",
        "TRGSR", "TRGSU", "TRI", "TRIB", "TRIN", "TRINI", "TRINZ", "TRIP", "TRMB", "TRMD",
        "TRMK", "TRN", "TRNO", "TRNR", "TRNS", "TRON", "TROO", "TROW", "TROX", "TRP",
        "TRS", "TRSG", "TRST", "TRT", "TRTN^A", "TRTN^B", "TRTN^C", "TRTN^D", "TRTN^E", "TRTN^F",
        "TRTN^G", "TRTX", "TRTX^C", "TRU", "TRUG", "TRUP", "TRV", "TRVG", "TRVI", "TRX",
        "TS", "TSAT", "TSBK", "TSCO", "TSEM", "TSHA", "TSI", "TSLA", "TSLX", "TSM",
        "TSN", "TSQ", "TSSI", "TSUI", "TT", "TTAM", "TTAN", "TTC", "TTD", "TTE",
        "TTEC", "TTEK", "TTGT", "TTI", "TTMI", "TTRX", "TTWO", "TU", "TULP", "TURB",
        "TUSK", "TUYA", "TV", "TVA", "TVACU", "TVACW", "TVAI", "TVAIR", "TVC", "TVE",
        "TVGN", "TVGNW", "TVRD", "TVTX", "TW", "TWAV", "TWFG", "TWG", "TWI", "TWIN",
        "TWLO", "TWLV", "TWLVU", "TWN", "TWO", "TWO^A", "TWO^B", "TWO^C", "TWOD", "TWST",
        "TX", "TXG", "TXMD", "TXN", "TXNM", "TXO", "TXRH", "TXT", "TY", "TY^",
        "TYG", "TYGO", "TYL", "TYRA", "TZOO", "U", "UA", "UAA", "UAC", "UAL",
        "UAMY", "UAN", "UAVS", "UBCP", "UBER", "UBS", "UBSI", "UBXG", "UCAR", "UCB",
        "UCL", "UCTT", "UDMY", "UDR", "UE", "UEC", "UEIC", "UFCS", "UFG", "UFI",
        "UFPI", "UFPT", "UG", "UGI", "UGP", "UGRO", "UHAL", "UHG", "UHGWW", "UHS",
        "UHT", "UI", "UIS", "UK", "UL", "ULBI", "ULCC", "ULH", "ULS", "ULTA",
        "UMAC", "UMBF", "UMBFO", "UMC", "UMH", "UMH^D", "UNB", "UNCY", "UNF", "UNFI",
        "UNH", "UNIT", "UNM", "UNMA", "UNP", "UNTY", "UONE", "UONEK", "UP", "UPB",
        "UPBD", "UPC", "UPLD", "UPS", "UPST", "UPWK", "UPXI", "URBN", "URG", "URGN",
        "URI", "UROY", "USA", "USAC", "USAR", "USAS", "USAU", "USB", "USB^A", "USB^H",
        "USB^P", "USB^Q", "USB^R", "USB^S", "USBC", "USCB", "USEA", "USEG", "USFD", "USGO",
        "USGOW", "USIO", "USLM", "USNA", "USPH", "UTF", "UTG", "UTHR", "UTI", "UTL",
        "UTMD", "UTSI", "UTZ", "UUU", "UUUU", "UVE", "UVSP", "UVV", "UWMC", "UXIN",
        "UYSC", "UZD", "UZE", "UZF", "V", "VABK", "VAC", "VACH", "VACHW", "VACI",
        "VAL", "VALE", "VALN", "VALU", "VANI", "VATE", "VAVX", "VBF", "VBIX", "VBNK",
        "VC", "VCEL", "VCIG", "VCTR", "VCV", "VCX", "VCYT", "VECO", "VEEA", "VEEAW",
        "VEEE", "VEEV", "VEL", "VELO", "VENU", "VEON", "VERA", "VERI", "VERU", "VERX",
        "VET", "VFC", "VFF", "VFL", "VFS", "VFSWW", "VG", "VGAS", "VGASW", "VGI",
        "VGM", "VGNT", "VGZ", "VHC", "VHCP", "VHCPU", "VHI", "VHUB", "VIA", "VIASP",
        "VIAV", "VICI", "VICR", "VIK", "VINP", "VIOT", "VIPS", "VIR", "VIRC", "VIRT",
        "VISN", "VIST", "VITL", "VIV", "VIVO", "VIVS", "VKI", "VKQ", "VKTX", "VLGEA",
        "VLN", "VLO", "VLRS", "VLT", "VLTO", "VLY", "VLYPN", "VLYPO", "VLYPP", "VMAR",
        "VMC", "VMD", "VMET", "VMI", "VMO", "VNCE", "VNDA", "VNET", "VNME", "VNMEU",
        "VNO", "VNO^L", "VNO^M", "VNO^N", "VNO^O", "VNOM", "VNRX", "VNT", "VNTG", "VOC",
        "VOD", "VOR", "VOXR", "VOYA", "VOYA^B", "VOYG", "VPG", "VPV", "VRA", "VRAX",
        "VRCA", "VRDN", "VRE", "VREX", "VRM", "VRME", "VRNS", "VRRM", "VRSK", "VRSN",
        "VRT", "VRTS", "VRTX", "VS", "VSA", "VSAT", "VSCO", "VSEC", "VSECU", "VSEE",
        "VSEEW", "VSH", "VSME", "VSNT", "VST", "VSTD", "VSTM", "VSTS", "VTAK", "VTEX",
        "VTGN", "VTIX", "VTMX", "VTN", "VTOL", "VTR", "VTRS", "VTS", "VTSI", "VTVT",
        "VUZI", "VVOS", "VVR", "VVV", "VVX", "VWAV", "VWAVW", "VYGR", "VYNE", "VYX",
        "VZ", "VZLA", "W", "WAB", "WABC", "WAFD", "WAFDP", "WAFU", "WAI", "WAL",
        "WAL^A", "WALD", "WALDW", "WASH", "WAT", "WATT", "WAVE", "WAY", "WB", "WBD",
        "WBI", "WBS", "WBS^F", "WBS^G", "WBTN", "WBUY", "WBX", "WCC", "WCN", "WCT",
        "WD", "WDAY", "WDC", "WDFC", "WDH", "WDI", "WDS", "WEA", "WEAV", "WEC",
        "WELL", "WEN", "WENN", "WENNW", "WERN", "WES", "WEST", "WETH", "WETO", "WEX",
        "WEYS", "WF", "WFC", "WFC^A", "WFC^C", "WFC^D", "WFC^L", "WFC^Y", "WFC^Z", "WFCF",
        "WFF", "WFG", "WFRD", "WGO", "WGRX", "WGS", "WGSWW", "WH", "WHD", "WHF",
        "WHFCL", "WHG", "WHLR", "WHLRD", "WHLRP", "WHR", "WHR^A", "WHWK", "WIA", "WILC",
        "WIMI", "WINA", "WING", "WIT", "WIW", "WIX", "WK", "WKC", "WKEY", "WKHS",
        "WKSP", "WLAC", "WLACW", "WLDN", "WLDS", "WLDSW", "WLFC", "WLII", "WLIIU", "WLIIW",
        "WLK", "WLKP", "WLTH", "WLY", "WLYB", "WM", "WMB", "WMG", "WMK", "WMS",
        "WMT", "WNC", "WNEB", "WNW", "WOK", "WOLF", "WOOF", "WOR", "WPAC", "WPC",
        "WPM", "WPP", "WPRT", "WRAP", "WRB", "WRB^E", "WRB^F", "WRB^G", "WRB^H", "WRBY",
        "WRD", "WRLD", "WRN", "WS", "WSBC", "WSBCO", "WSBF", "WSBK", "WSC", "WSFS",
        "WSHP", "WSM", "WSO", "WSO/B", "WSR", "WST", "WSTN", "WSTNR", "WSTNU", "WT",
        "WTBA", "WTF", "WTFC", "WTFCN", "WTG", "WTI", "WTM", "WTO", "WTRG", "WTS",
        "WTTR", "WTW", "WU", "WULF", "WVE", "WVVI", "WVVIP", "WW", "WWD", "WWR",
        "WWW", "WXM", "WY", "WYFI", "WYHG", "WYNN", "WYY", "XAIR", "XBIO", "XBIT",
        "XBP", "XBPEW", "XCBE", "XCBEU", "XCH", "XCUR", "XE", "XEL", "XELB", "XELLL",
        "XENE", "XERS", "XFLH", "XFLT", "XFOR", "XGN", "XHG", "XHLD", "XHR", "XIFR",
        "XLO", "XMTR", "XNCR", "XNDU", "XNET", "XOM", "XOMA", "XOMAO", "XOMAP", "XOS",
        "XOSWW", "XP", "XPEL", "XPER", "XPEV", "XPL", "XPO", "XPOF", "XPON", "XPRO",
        "XRAY", "XRN", "XRN^A", "XRN^B", "XRPN", "XRPNU", "XRPNW", "XRTX", "XRX", "XRXDW",
        "XSLL", "XSLLU", "XSLLW", "XTIA", "XTLB", "XTNT", "XWEL", "XWIN", "XXI", "XXII",
        "XYF", "XYL", "XYZ", "XZO", "YAAS", "YALA", "YB", "YCBD", "YCY", "YDDL",
        "YDES", "YDESW", "YDKG", "YELP", "YETI", "YEXT", "YHC", "YHGJ", "YHNA", "YHNAR",
        "YI", "YIBO", "YJ", "YMAT", "YMM", "YMT", "YOOV", "YORW", "YOU", "YOUL",
        "YPF", "YQ", "YRD", "YSG", "YSS", "YSWY", "YSXT", "YTRA", "YUM", "YUMC",
        "YXT", "YYAI", "YYGH", "Z", "ZBAI", "ZBAO", "ZBH", "ZBIO", "ZBRA", "ZCMD",
        "ZD", "ZDAI", "ZDGE", "ZENA", "ZEO", "ZEOWW", "ZEPP", "ZETA", "ZG", "ZGN",
        "ZH", "ZIM", "ZION", "ZIONP", "ZIP", "ZJK", "ZJYL", "ZKH", "ZKIN", "ZKP",
        "ZKPW", "ZLAB", "ZM", "ZNB", "ZNTL", "ZONE", "ZOOZ", "ZOOZW", "ZS", "ZSPC",
        "ZSTK", "ZTEK", "ZTG", "ZTO", "ZTR", "ZTS", "ZUMZ", "ZURA", "ZVIA", "ZVRA",
        "ZWS", "ZYBT", "ZYME",
    ]


def _cad_seed():
    return [
        "RY.TO", "TD.TO", "BNS.TO", "BMO.TO", "CM.TO",
        "CNR.TO", "CP.TO", "ENB.TO", "TRP.TO", "SU.TO",
        "ABX.TO", "WPM.TO", "AEM.TO", "K.TO", "FM.TO",
        "SLF.TO", "MFC.TO", "GWO.TO", "IAG.TO", "POW.TO",
        "ATD.TO", "MRU.TO", "L.TO", "EMP-A.TO", "DOL.TO",
    ]


# ── Data Fetcher ──────────────────────────────────────────────────────────────

def fetch_fundamentals(ticker: str) -> dict:
    try:
        t    = yf.Ticker(ticker)
        info = t.info
        hist = t.history(period="1y")

        if hist.empty or len(hist) < 50:
            return {"ticker": ticker, "error": "Insufficient price history"}

        close = hist["Close"]
        ma50  = float(close.rolling(50).mean().iloc[-1])
        ma200 = float(close.rolling(200).mean().iloc[-1]) if len(close) >= 200 else None
        price = float(close.iloc[-1])

        delta = close.diff()
        gain  = delta.clip(lower=0).rolling(14).mean()
        loss  = (-delta.clip(upper=0)).rolling(14).mean()
        rs    = gain / loss
        rsi   = float((100 - 100 / (1 + rs)).iloc[-1])

        fcf        = info.get("freeCashflow")
        div_yield  = info.get("dividendYield") or 0
        roe        = info.get("returnOnEquity")
        net_debt   = (info.get("totalDebt") or 0) - (info.get("totalCash") or 0)
        ebitda     = info.get("ebitda")
        market_cap = info.get("marketCap")
        rev_growth = info.get("revenueGrowth")
        sector     = info.get("sector", "Unknown")
        name       = info.get("shortName", ticker)

        net_debt_ebitda = (net_debt / ebitda) if ebitda else None
        fcf_yield       = (fcf / market_cap)  if (fcf and market_cap) else None

        return {
            "ticker":          ticker,
            "name":            name,
            "sector":          sector,
            "price":           round(price, 2),
            "ma50":            round(ma50, 2),
            "ma200":           round(ma200, 2) if ma200 is not None else None,
            "rsi":             round(rsi, 2),
            "roe":             round(roe, 4)             if roe             is not None else None,
            "net_debt_ebitda": round(net_debt_ebitda, 2) if net_debt_ebitda is not None else None,
            "fcf_yield":       round(fcf_yield, 4)       if fcf_yield       is not None else None,
            "div_yield":       round(div_yield, 4),
            "rev_growth":      round(rev_growth, 4)      if rev_growth      is not None else None,
            "error":           None,
        }
    except Exception as e:
        return {"ticker": ticker, "error": str(e)}


# ── Rating Engine ─────────────────────────────────────────────────────────────

def rate_stock(d: dict) -> dict:
    if d.get("error"):
        return {**d, "rating": "N/A", "thesis": "Data error", "risk": d["error"], "score": None}

    score = 0
    flags = []
    risks = []

    # Trend
    if d["ma200"] and d["price"] > d["ma50"] > d["ma200"]:
        score += 2
        flags.append("above 50/200 MA")
    elif d["ma200"] and d["price"] < d["ma200"]:
        score -= 2
        flags.append("below 200 MA")

    # Momentum
    if 40 <= d["rsi"] <= 65:
        score += 1
    elif d["rsi"] > 75:
        score -= 1
        risks.append("overbought RSI")
    elif d["rsi"] < 30:
        score += 1
        flags.append("oversold — mean reversion candidate")

    # Quality: ROE
    if d["roe"] and d["roe"] > 0.12:
        score += 1
        flags.append(f"ROE {d['roe']*100:.1f}%")
    elif d["roe"] and d["roe"] < 0:
        score -= 1
        risks.append("negative ROE")

    # Leverage
    if d["net_debt_ebitda"] is not None:
        if d["net_debt_ebitda"] < 4.0:
            score += 1
        elif d["net_debt_ebitda"] > 6.0:
            score -= 2
            risks.append(f"high leverage {d['net_debt_ebitda']:.1f}x")

    # FCF vs Dividend (Schilit forensic check)
    if d["fcf_yield"] is not None:
        if d["fcf_yield"] > d["div_yield"]:
            score += 1
            flags.append("FCF covers dividend")
        elif d["div_yield"] > 0 and d["fcf_yield"] < d["div_yield"]:
            score -= 1
            risks.append("dividend not covered by FCF")

    # Growth
    if d["rev_growth"] and d["rev_growth"] > 0.15:
        score += 1
        flags.append(f"rev growth {d['rev_growth']*100:.1f}%")

    rating = "BUY" if score >= 4 else ("HOLD" if score >= 1 else "SELL")
    thesis = "; ".join(flags) if flags else "No strong signals"
    risk   = "; ".join(risks) if risks else "Execution risk / macro headwinds"

    return {**d, "rating": rating, "thesis": thesis, "risk": risk, "score": score}


# ── Main Runner ───────────────────────────────────────────────────────────────

def run_analysis(seed_fn, label: str) -> list:
    tickers = seed_fn()
    print(f"[{label}] Analysing {len(tickers)} tickers...")
    results = []
    for t in tickers:
        rated = rate_stock(fetch_fundamentals(t))
        rated["market"] = label
        if rated.get("rating") != "N/A":
            results.append(rated)
    results.sort(key=lambda x: (x.get("score") or -99), reverse=True)
    return results


if __name__ == "__main__":
    os.makedirs("public", exist_ok=True)

    usd_results = run_analysis(_usd_seed, "USD")
    cad_results = run_analysis(_cad_seed, "CAD")

    all_results = usd_results + cad_results

    out_path = "public/recommendations.json"
    with open(out_path, "w") as f:
        json.dump(all_results, f, indent=2)

    print(f"\n✅ Wrote {len(all_results)} recommendations to {out_path}")
    print(f"   USD: {len(usd_results)} | CAD: {len(cad_results)}")
