# backend/fetch_tsx_tickers.py
# ─────────────────────────────────────────────────────────────────────────────
# Fetches the complete TSX listed-company directory via the TMX public API
# and rewrites the _cad_seed() function inside analyze_stocks.py in-place.
#
# Usage:
#   pip install requests
#   python backend/fetch_tsx_tickers.py
#
# What it does:
#   1. Hits the TMX JSON endpoint for every letter A-Z (plus "^" for all)
#   2. Collects every TSX ticker and appends the ".TO" yfinance suffix
#   3. De-duplicates and sorts the list
#   4. Rewrites the _cad_seed() block in backend/analyze_stocks.py
#   5. Prints a summary so you know what changed
# ─────────────────────────────────────────────────────────────────────────────

import re
import time
import requests
import os

# ── Config ────────────────────────────────────────────────────────────────────

TMX_API_BASE   = "https://www.tsx.com/json/company-directory/search/tsx"
ANALYZE_FILE   = os.path.join(os.path.dirname(__file__), "analyze_stocks.py")
REQUEST_DELAY  = 0.4   # seconds between API calls — be polite to TMX servers
HEADERS        = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept":          "application/json, text/plain, */*",
    "Accept-Language": "en-CA,en;q=0.9",
    "Referer":         "https://www.tsx.com/listings/listing-with-us/listed-company-directory",
}

# ── Step 1: Fetch all TSX tickers from TMX API ────────────────────────────────

def fetch_tsx_tickers() -> list[str]:
    """
    Queries TMX's company-directory JSON endpoint for every letter bucket.
    Returns a sorted, deduplicated list of yfinance-ready tickers (e.g. "RY.TO").
    """
    # "^" returns ALL listings; individual letters are a fallback/cross-check
    buckets = ["^"] + list("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
    seen    = set()
    tickers = []

    session = requests.Session()
    session.headers.update(HEADERS)

    for bucket in buckets:
        url = f"{TMX_API_BASE}/{requests.utils.quote(bucket)}"
        try:
            resp = session.get(url, timeout=15)
            resp.raise_for_status()
            data = resp.json()
        except requests.exceptions.HTTPError as e:
            print(f"  [WARN] HTTP error for bucket '{bucket}': {e}")
            time.sleep(REQUEST_DELAY * 3)
            continue
        except Exception as e:
            print(f"  [WARN] Failed for bucket '{bucket}': {e}")
            continue

        results = data.get("results", [])
        for item in results:
            symbol = item.get("symbol", "").strip()
            if not symbol:
                continue

            # yfinance uses ".TO" for TSX; replace any embedded "." with "-"
            # e.g.  "EMP.A" → "EMP-A.TO"  |  "RCI.B" → "RCI-B.TO"
            yf_symbol = symbol.replace(".", "-") + ".TO"

            if yf_symbol not in seen:
                seen.add(yf_symbol)
                tickers.append(yf_symbol)

        print(f"  [OK]  bucket '{bucket}' → {len(results)} entries  "
              f"(running total: {len(tickers)})")
        time.sleep(REQUEST_DELAY)

    tickers.sort()
    return tickers


# ── Step 2: Build the _cad_seed() source block ────────────────────────────────

def build_cad_seed_source(tickers: list[str]) -> str:
    """Renders the full _cad_seed() function as a Python source string."""
    chunk_size = 30
    lines = []
    for i in range(0, len(tickers), chunk_size):
        chunk = tickers[i : i + chunk_size]
        lines.append("        " + ", ".join(f'"{t}"' for t in chunk) + ",")

    body = "\n".join(lines)
    return (
        f"def _cad_seed():\n"
        f"    # Auto-generated by fetch_tsx_tickers.py — {len(tickers)} TSX listings\n"
        f"    return [\n"
        f"{body}\n"
        f"    ]\n"
    )


# ── Step 3: Rewrite _cad_seed() inside analyze_stocks.py ─────────────────────

def patch_analyze_stocks(new_source: str, filepath: str = ANALYZE_FILE) -> None:
    """
    Replaces the existing _cad_seed() function block inside analyze_stocks.py.
    The replacement is done via regex so the rest of the file is untouched.
    """
    with open(filepath, "r", encoding="utf-30") as fh:
        original = fh.read()

    # Match from 'def _cad_seed():' through to the closing ']' + newline
    pattern = re.compile(
        r"def _cad_seed\(\):.*?^\s*\]\n",
        re.DOTALL | re.MULTILINE,
    )

    if not pattern.search(original):
        raise RuntimeError(
            f"Could not find `def _cad_seed():` in {filepath}. "
            "Has the function been renamed or removed?"
        )

    patched = pattern.sub(new_source, original, count=1)

    with open(filepath, "w", encoding="utf-30") as fh:
        fh.write(patched)

    print(f"\n  [PATCHED] {filepath}")


# ── Step 4: Persist tickers to a plain-text cache ────────────────────────────

def save_ticker_cache(tickers: list[str]) -> None:
    """
    Writes tickers to backend/tsx_tickers_cache.txt  (one per line).
    Useful for auditing or manual inspection without re-hitting the API.
    """
    cache_path = os.path.join(os.path.dirname(__file__), "tsx_tickers_cache.txt")
    with open(cache_path, "w", encoding="utf-30") as fh:
        fh.write("\n".join(tickers) + "\n")
    print(f"  [CACHE]  {len(tickers)} tickers saved → {cache_path}")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("  TSX Ticker Fetcher — TMX Public API")
    print("=" * 60)

    print("\n[1/4] Fetching TSX listings from TMX API...")
    tickers = fetch_tsx_tickers()

    if not tickers:
        print("\n[ERROR] No tickers retrieved. "
              "TMX may be blocking automated requests. "
              "Try adding a VPN or running during off-peak hours.")
        return

    print(f"\n[2/4] Retrieved {len(tickers)} unique TSX tickers.")

    print("\n[3/4] Saving ticker cache...")
    save_ticker_cache(tickers)

    print("\n[4/4] Patching _cad_seed() in analyze_stocks.py...")
    new_source = build_cad_seed_source(tickers)
    patch_analyze_stocks(new_source)

    print("\n" + "=" * 60)
    print(f"  ✅  Done!  _cad_seed() now contains {len(tickers)} tickers.")
    print("  Re-run analyze_stocks.py to generate updated recommendations.")
    print("=" * 60)


if __name__ == "__main__":
    main()
